// GENERATED by garmin/tools/tree-sprites.js - do not edit.
using Toybox.WatchUi;

// The tree sprite resources, [type][size] - type is TREE_TYPES (round, broadleaf, pine, yellow_green),
// size indexes SIZES. PAD_FRACTION is the shadow pad beyond the nominal crown size.
module GarminTreeSpriteIds {
    const SIZES = [8, 12, 16, 22, 28];
    const PAD_FRACTION = 0.14;
    function amoled() {
        return [
        [Rez.Drawables.TreeA0_8, Rez.Drawables.TreeA0_12, Rez.Drawables.TreeA0_16, Rez.Drawables.TreeA0_22, Rez.Drawables.TreeA0_28],
        [Rez.Drawables.TreeA1_8, Rez.Drawables.TreeA1_12, Rez.Drawables.TreeA1_16, Rez.Drawables.TreeA1_22, Rez.Drawables.TreeA1_28],
        [Rez.Drawables.TreeA2_8, Rez.Drawables.TreeA2_12, Rez.Drawables.TreeA2_16, Rez.Drawables.TreeA2_22, Rez.Drawables.TreeA2_28],
        [Rez.Drawables.TreeA3_8, Rez.Drawables.TreeA3_12, Rez.Drawables.TreeA3_16, Rez.Drawables.TreeA3_22, Rez.Drawables.TreeA3_28]
    ];
    }
    function mip() {
        return [
        [Rez.Drawables.TreeM0_8, Rez.Drawables.TreeM0_12, Rez.Drawables.TreeM0_16, Rez.Drawables.TreeM0_22, Rez.Drawables.TreeM0_28],
        [Rez.Drawables.TreeM1_8, Rez.Drawables.TreeM1_12, Rez.Drawables.TreeM1_16, Rez.Drawables.TreeM1_22, Rez.Drawables.TreeM1_28],
        [Rez.Drawables.TreeM2_8, Rez.Drawables.TreeM2_12, Rez.Drawables.TreeM2_16, Rez.Drawables.TreeM2_22, Rez.Drawables.TreeM2_28],
        [Rez.Drawables.TreeM3_8, Rez.Drawables.TreeM3_12, Rez.Drawables.TreeM3_16, Rez.Drawables.TreeM3_22, Rez.Drawables.TreeM3_28]
    ];
    }
}
