const assert = require("assert");
const fs = require("fs");
const path = require("path");
const ROOT = path.join(__dirname, "..");
const read = p => fs.readFileSync(path.join(ROOT, p), "utf8");
const sql = read("supabase/migrations/20260905234029_canonical_players_identity.sql");
const admin = read("functions/caddy-admin-users.js");
const signup = read("functions/auth-signup.js");
const auth = read("functions/auth-utils.js");
const ui = read("scripts/clarity-admin-users.js");

assert.match(sql, /create table if not exists public\.caddy_players/i);
assert.match(sql, /auth_user_id uuid unique/i);
assert.match(sql, /Multiple unclaimed players match this email/i);
assert.match(sql, /caddy_coach_player_assignments/i);
assert.match(sql, /unique \(coach_player_id, player_id\)/i);
assert.match(sql, /caddy_player_merge_aliases/i);
assert.match(sql, /caddy_execute_player_merge/i);
assert.match(sql, /Cannot merge a player into themselves/i);
assert.match(sql, /Two Auth logins require explicit confirmation/i);
assert.match(sql, /bagChoice/i);
assert.match(sql, /practice_native_shots/i);
assert.match(sql, /user_entitlements/i);
assert.match(sql, /alter table public\.caddy_players enable row level security/i);
assert.match(sql, /to service_role/i);
assert.match(admin, /requireAdmin/);
assert.match(admin, /action === "merge_preview"/);
assert.match(admin, /action === "merge_execute"/);
assert.match(admin, /action === "assign_coach"/);
assert.match(signup, /claimCanonicalPlayer/);
assert.ok(signup.indexOf("const claimed = await claimCanonicalPlayer") < signup.indexOf("const pack = await upsertAccount"), "claim must occur before compatibility account/profile creation");
assert.match(auth, /caddy_claim_or_create_player/);
assert.match(ui, /Create no-login player/);
assert.match(ui, /Assign Sam Hale/);
console.log("canonical users tests passed");
