const assert = require("assert");
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const appCore = fs.readFileSync(path.join(root, "scripts", "gd-app-core.js"), "utf8");
const pickerSearch = fs.readFileSync(path.join(root, "scripts", "inline", "gd-course-picker-search-v2.js"), "utf8");
const pickerBaseCss = fs.readFileSync(path.join(root, "styles", "inline", "gd-app-base.css"), "utf8");
const gpsRuntimeCss = fs.readFileSync(path.join(root, "styles", "inline", "gd-gps-play-runtime-owner-v1-css.css"), "utf8");
const gpsRuntime = fs.readFileSync(path.join(root, "scripts", "inline", "gd-gps-play-runtime-owner-v1.js"), "utf8");
const brandRail = fs.readFileSync(path.join(root, "scripts", "inline", "gd-brand-icon-render.js"), "utf8");
const betaShell = fs.readFileSync(path.join(root, "scripts", "inline", "gd-gps-beta-mode-shell.js"), "utf8");
const gpsRequestButton = fs.readFileSync(path.join(root, "scripts", "inline", "gd-gps-request-button-fix-v1.js"), "utf8");
const library = fs.readFileSync(path.join(root, "scripts", "gd-course-library-pin-lock.js"), "utf8");

for (const [label, source] of [["index.html", index], ["gd-course-library-pin-lock.js", library]]) {
  assert(!/-36\.9149|174\.7255/.test(source), `${label} must not contain the old Maungakiekie fallback coordinate`);
}

assert(appCore.includes("const GD_NEUTRAL_MAP_CENTER=[0,0];"), "map boots to a neutral technical center");
assert(appCore.includes("return null;\n}\nfunction gdAssumedCourseLabelForPicker"), "course picker returns no default point when location is unknown");
assert(pickerSearch.includes("requestPickerGps();"), "course picker requests GPS for nearby suggestions");
assert(pickerSearch.includes("window.gdCoursePickerRequestGps=requestPickerGps"), "home/play route can request picker GPS from a user click");
assert(pickerSearch.includes("window.gdCoursePickerCenterMapOnGps=centerPickerMapOnGps"), "course picker can center the live map on the latest GPS fix");
assert(pickerSearch.includes("map.setView([Number(point.lat),Number(point.lng)],zoom,{animate:false})"), "GPS fix recenters the map behind the course picker");
assert(pickerSearch.includes("const gps=recentGpsPoint();"), "course picker ranking uses actual recent GPS when available");
assert(pickerSearch.includes('if(/manual|tap|click|map|green-focus|pin/.test(source))return null;'), "course picker search ignores simulated/map-derived points as GPS");
assert(pickerSearch.includes("return distanceDelta;"), "GPS course ties prefer the closest course");
assert(pickerSearch.includes("const course=basePayload({"), "recent course rows are sanitized before re-entering the course picker flow");
assert(appCore.includes("const setCourseView=opts.setCourseView!==undefined?!!opts.setCourseView:hasCoursePoint;"), "selected search/course coordinates drive the map view");
assert(appCore.includes("if(!Number.isFinite(at)||at<=0||Date.now()-at>maxAgeMs)return null;"), "course picker requires a timestamped recent GPS fix");
assert(appCore.includes("function gdResetCoursePickerPresentationReadiness(payload,opts={})"), "new course selections clear stale captured presentation readiness");
assert(appCore.includes("if(!gdCoursePickerHasMappedPlayData(payload,1))return false;"), "course picker only opens mapped start when the selected course has mapped play data");
assert(appCore.includes('document.body.dataset.gdCourseNeedsPin=result&&result.fallback?"active":result&&result.playable?"no":"pending";'), "course picker records when the pin fallback owns unresolved courses");
assert(appCore.includes("function gdCoursePickerNeedsCoursePin(payload)"), "course picker can detect when a no-GPS course pick needs a pin screen");
assert(appCore.includes("payload?.gdDatabaseMapAvailable===true"), "published database maps beat the pin prompt");
assert(!appCore.includes('mark("stored-pin");return false;'), "stored pins prefill the pin screen but do not bypass it");
assert(!appCore.includes('mark("recent-live-gps");return false;'), "recent GPS does not bypass the no-database-map pin screen");
assert(appCore.includes("function gdCoursePickerCheckDatabaseThenOpen(payload)"), "course picker checks the database map before deciding whether to pin");
assert(!appCore.includes("published-course-visual"), "course visuals do not count as database maps for the picker pin gate");
assert(appCore.includes("if(!payload.gdDatabaseMapChecked&&!gdCoursePayloadIsManual(payload))return gdCoursePickerCheckDatabaseThenOpen(payload);"), "course picker gates non-manual course opens behind a database map check");
assert(appCore.includes("if(gdCoursePickerNeedsCoursePin(payload))return gdShowCoursePinScreen(payload);"), "no-GPS course picks show the pin screen before course play opens");
assert(appCore.includes('mark("needs-pin")'), "pin decision writes a DOM breadcrumb for live QA");
assert(appCore.includes("const usePinSeed=!payload.gdDatabaseMapAvailable&&gdCoursePickerUsesPinSeed(payload);"), "database maps win over stored pin scanner seeds");
assert(appCore.includes('reason:pinSeed?"course-picker-pin":"course-picker"'), "confirmed pins feed the course scanner as the mapping reason");
assert(appCore.includes("courseCentre:pinnedCentre||undefined"), "confirmed pins feed the course scanner as the mapping centre");
assert(appCore.includes("allowLocalSavedMap:payload?.gdDatabaseMapAvailable===true"), "local saved maps cannot beat the picker pin flow without a confirmed database map");
assert(appCore.includes("acceptPartialGeneratedMap:pinSeed"), "pin-seeded scans can open the generated first hole without waiting for a full database publish");
assert(appCore.includes("Promise.resolve(pinSeed?null:gdLoadCourseVisualForPlay"), "pin-seeded scans do not get pre-empted by course visuals");
assert(appCore.includes("if(payload?.gdDatabaseMapAvailable===true)gdScheduleCourseVisualPullForPlay(payload);"), "course visual pulls only follow confirmed database maps");
assert(appCore.includes("window.gdConfirmCoursePin=gdConfirmCoursePin"), "pin confirmation is exposed for the picker panel");
assert(pickerBaseCss.includes(".courseScreen{position:absolute;inset:0;z-index:7600;background:transparent"), "course picker overlay leaves the live map visible behind the controls");
assert(pickerBaseCss.includes(".gdCoursePinScreen"), "course picker includes the no-GPS pin prompt styling");
assert(pickerBaseCss.includes(".courseScreen.gdCoursePinMode #gdCourseResumeRound{display:none!important}"), "pin mode hides the stale resume-round panel");
assert(gpsRuntimeCss.includes("body.shell-gps.gdCoursePickerOpen #map"), "GPS runtime CSS keeps the map visible under the course picker");
assert(gpsRuntime.includes('document.body.dataset.gdGpsMapVisibilityState=pickerOpen()?"picker-live-map":"not-gps"'), "GPS runtime owner treats picker as a live-map state");
assert(gpsRuntime.includes('document.body.dataset.gdCourseNeedsPin==="choose-course-pin"'), "GPS wrapper does not start a resume round while the pin prompt is active");
assert(!index.includes('class="rightRail" id="gdAppRightRail"'), "right rail is no longer static boot markup that can flash over the picker");
assert(brandRail.includes("function railAllowed()"), "brand rail script owns rail creation instead of static HTML");
assert(brandRail.includes("removeRightRail();"), "brand rail script deletes the rail while picker/home surfaces own the screen");
assert(brandRail.includes("gdAuthLocked") && brandRail.includes("gdProfileOpen"), "brand rail script does not keep a hidden rail on auth/profile screens");
assert(brandRail.includes("window.gdEnsureAppRightRail = ensureRightRail;"), "runtime owner can request a rail only when GPS play needs it");
assert(gpsRuntime.includes('if(!rail&&typeof window.gdEnsureAppRightRail==="function")rail=window.gdEnsureAppRightRail();'), "GPS runtime creates the rail through the rail owner");
assert(betaShell.includes("if(!gpsActive()){"), "legacy beta shell does not attach mode switch while picker is active");
assert(gpsRequestButton.includes("if(!rail)return;"), "GPS request helper treats missing rail as intentional");
assert(library.includes("return recentGpsPoint();"), "library session center falls back only to actual recent GPS");
assert(library.includes("lat:finder?.lat??saved.courseLat??null"), "course library open does not invent coordinates");
assert(library.includes("course?loadUserCourseData(userId(),courseId(course)):loadUserCourseData()"), "mapped checks load the explicit selected course instead of stale active course data");
assert(library.includes("const hasTrustedPlayData=requestedHolePlayable(course,expected);"), "settled course-open UI requires trusted mapped data for the requested hole");
assert(library.includes("async function publishedCourseMapAvailability(course,opts={})"), "course library exposes a DB-map-only availability check for the picker");
assert(library.includes("function courseDataMapReadiness(course,hole,wholeCourse)"), "database map availability checks the published course data directly");
assert(library.includes("saved-map-ignored-without-database-map"), "course scanner ignores local saved maps when the picker did not confirm a database map");
assert(library.includes("mode:syncMode"), "generated course scans post to the database as a create-or-append upload");
assert(pickerSearch.includes('const COURSE_MAPS_API="/api/course-maps";'), "course picker searches the shared course-map database");
assert(pickerSearch.includes("function loadDatabaseCourses(opts={})"), "course picker hydrates database courses behind the search UI");
assert(pickerSearch.includes('source:"database-course"'), "database courses are tagged when merged into picker results");
assert(pickerSearch.includes("hasDatabaseMap=true"), "database course results keep a database-map flag for picker ranking");
assert(index.includes("gd-app-base.css?v=course-picker-live-gps-pin-20260718"), "base CSS cache-bust ships the pin prompt styling");
assert(index.includes("gd-app-core.js?v=boot-crash-fix-20260719"), "app core cache-bust ships the flagTool boot-crash fix");
assert(index.includes("gd-gps-beta-mode-shell.js?v=course-picker-rail-owner-20260719"), "beta GPS shell cache-bust ships rail owner handoff");
assert(index.includes("gd-brand-icon-render.js?v=boot-crash-fix-20260719"), "brand rail cache-bust ships dynamic rail ownership + flag handler rebind");
assert(index.includes("gd-course-picker-search-v2.js?v=course-picker-owner-cleanup-20260719"), "course picker search cache-bust ships database course hydration");
assert(index.includes("gd-course-library-pin-lock.js?v=course-picker-db-search-sync-20260718"), "course library cache-bust ships generated scan upload");
assert(index.includes("gd-gps-request-button-fix-v1.js?v=course-picker-rail-owner-20260719"), "GPS request button cache-bust ships optional rail handling");
assert(index.includes("gd-gps-play-runtime-owner-v1.js?v=course-picker-rail-owner-20260719"), "GPS runtime cache-bust ships the pin prompt wrapper guard");

console.log("course-picker-location tests passed");
