import CoreGraphics
import Foundation

/* The Watch half of the "lite map" contract baked by scripts/gd-watch-map-core.js.

 A lite map is one flat vector-drawn image per hole plus the spatial reference
 needed to put a GPS coordinate on it. Nothing here re-derives geometry: the
 phone never sends course objects to the wrist, only the baked image and the
 four transform coefficients the generator already committed to.

 The projection is a deliberate line-for-line mirror of the generator's
 worldPx/applyTransform/invertTransform. If these two ever disagree the marker
 lands in the wrong place with no error to show for it, so the maths is copied
 rather than approximated — and dev/watch-map-projection.test.js pins the same
 numbers on the JavaScript side.

 Everything is Double, never Float: a z20 world pixel is ~2.7e8 and the
 transform's translation terms are larger still, so single precision would lose
 metres of accuracy inside an image only a few hundred pixels wide. */
struct WatchMapSpatialReference: Codable, Equatable {
    static let supportedVersion = 1
    private static let tileSize: Double = 256
    private static let maxMercatorLatitude: Double = 85.05112878

    let version: Int
    let refZoom: Int
    let transform: Transform
    let imageWidth: Double
    let imageHeight: Double
    let rotationDegrees: Double?
    let metresPerPixel: Double?

    struct Transform: Codable, Equatable {
        let a: Double
        let b: Double
        let tx: Double
        let ty: Double
    }

    /* A package generated by a newer recipe, or one whose transform is
       degenerate, is unusable rather than approximately usable — the caller
       shows the numbers-only face instead of a map with drifting markers. */
    var isUsable: Bool {
        guard version == Self.supportedVersion else { return false }
        guard imageWidth > 0, imageHeight > 0 else { return false }
        guard transform.a.isFinite, transform.b.isFinite, transform.tx.isFinite, transform.ty.isFinite else { return false }
        return transform.a * transform.a + transform.b * transform.b > 0
    }

    /// Image-pixel position of a real-world coordinate. Nil when the reference
    /// is unusable or the coordinate itself is not finite.
    func imagePoint(lat: Double, lng: Double) -> CGPoint? {
        guard isUsable, lat.isFinite, lng.isFinite else { return nil }
        let world = Self.worldPixel(lat: lat, lng: lng, zoom: refZoom)
        let x = transform.a * world.x - transform.b * world.y + transform.tx
        let y = transform.b * world.x + transform.a * world.y + transform.ty
        guard x.isFinite, y.isFinite else { return nil }
        return CGPoint(x: x, y: y)
    }

    /// Inverse of `imagePoint` — only used for diagnostics today, but it is the
    /// half that proves the transform round-trips.
    func coordinate(atImageX x: Double, y: Double) -> (lat: Double, lng: Double)? {
        guard isUsable else { return nil }
        let determinant = transform.a * transform.a + transform.b * transform.b
        let sx = x - transform.tx
        let sy = y - transform.ty
        let worldX = (transform.a * sx + transform.b * sy) / determinant
        let worldY = (transform.a * sy - transform.b * sx) / determinant
        let scale = Self.tileSize * pow(2, Double(refZoom))
        let n = Double.pi * (1 - (2 * worldY) / scale)
        let lat = atan(sinh(n)) * 180 / Double.pi
        let lng = (worldX / scale) * 360 - 180
        guard lat.isFinite, lng.isFinite else { return nil }
        return (lat, lng)
    }

    private static func worldPixel(lat: Double, lng: Double, zoom: Int) -> CGPoint {
        let scale = tileSize * pow(2, Double(zoom))
        let clamped = min(max(lat, -maxMercatorLatitude), maxMercatorLatitude)
        let latRad = clamped * Double.pi / 180
        return CGPoint(
            x: ((lng + 180) / 360) * scale,
            y: ((1 - log(tan(latRad) + 1 / cos(latRad)) / Double.pi) / 2) * scale
        )
    }
}

/* One hole's golf geometry, baked from the same course objects the image was
 drawn from and travelling with it.

 This is what lets the wrist answer a golf question locally instead of asking
 the phone: where the green is and what shape it is, and — when the hole has a
 mapped tee — the play line down it. `spatialReference` already turns any of
 these coordinates into a pixel on the delivered image.

 The play line is one fact and arrives whole or not at all: a hole with no
 mapped tee has `tee`, `route`, `bearingDeg` and `lengthM` all nil rather than a
 route measured from the green standing in for the tee. `greenShape` may be nil
 independently, because a green can be mapped as a centre with no outline.

 Nothing here is invented on this side. A hole that lacks what a calculation
 needs defers to the Scene's value; it never approximates one. */
struct WatchHoleReference: Codable, Equatable {
    static let supportedVersion = 1

    let version: Int
    let green: Coordinate
    let greenShape: [Coordinate]?
    let tee: Coordinate?
    let route: [Coordinate]?
    let bearingDeg: Double?
    let lengthM: Double?

    struct Coordinate: Codable, Equatable {
        let lat: Double
        let lng: Double
    }

    /* A reference from a newer recipe is refused rather than half-read, the
       same rule `WatchMapSpatialReference.isUsable` applies to the projection.
       Refusing costs the local calculation and nothing else — the hole still
       draws, and the Scene still carries the phone's answer. */
    var isUsable: Bool {
        version == Self.supportedVersion && green.isFinite
    }

    /* The green outline, only when it is one. A green mapped as a centre with
       no shape is normal and is not a fault. */
    var usableGreenShape: [Coordinate]? {
        guard let greenShape, greenShape.count >= 3, greenShape.allSatisfy({ $0.isFinite }) else { return nil }
        return greenShape
    }

    /* The hole's play line, present only when every part of it is. Callers ask
       for this rather than reading `route` and `tee` separately, so there is
       one place — not one per caller — that decides whether the wrist may
       reason down the hole. A missing play line never invalidates the green:
       the two answer different questions and only one of them needs a tee. */
    var playLine: PlayLine? {
        guard let tee, let route, let bearingDeg, let lengthM else { return nil }
        guard route.count >= 2, tee.isFinite, route.allSatisfy({ $0.isFinite }) else { return nil }
        guard bearingDeg.isFinite, lengthM.isFinite, lengthM > 0 else { return nil }
        return PlayLine(tee: tee, route: route, bearingDeg: bearingDeg, lengthM: lengthM)
    }

    struct PlayLine: Equatable {
        let tee: Coordinate
        let route: [Coordinate]
        let bearingDeg: Double
        let lengthM: Double
    }
}

extension WatchHoleReference.Coordinate {
    var isFinite: Bool { lat.isFinite && lng.isFinite }
}

/* One course's package as the phone describes it. `version` is the generator's
   millisecond package version; it is the whole cache key, because a regenerated
   package lands under a new version folder and never overwrites the old one. */
struct WatchMapManifest: Codable, Equatable {
    let courseKey: String
    let version: Int64
    let holes: [Hole]

    struct Hole: Codable, Equatable {
        let holeNumber: Int
        let asset: String
        let width: Double
        let height: Double
        let spatialReference: WatchMapSpatialReference
        /* The hole's golf geometry. Optional at the hole, because a package
           baked before the generator emitted one is still a perfectly good
           picture of a hole and must keep delivering. */
        let reference: WatchHoleReference?

        /* What callers should read: a reference that arrived from a newer
           recipe, or malformed, is nothing rather than something to guess
           from. It never costs the hole its image — only the local
           calculation, which falls back to the Scene. */
        var golfReference: WatchHoleReference? {
            guard let reference, reference.isUsable else { return nil }
            return reference
        }

        enum CodingKeys: String, CodingKey { case holeNumber, asset, width, height, spatialReference, reference }

        init(holeNumber: Int, asset: String, width: Double, height: Double, spatialReference: WatchMapSpatialReference, reference: WatchHoleReference?) {
            self.holeNumber = holeNumber
            self.asset = asset
            self.width = width
            self.height = height
            self.spatialReference = spatialReference
            self.reference = reference
        }

        /* Written out only because of the last line. The synthesized decoder
           would use decodeIfPresent for the optional reference, which THROWS on
           a present-but-malformed one — and a throw here fails the whole
           manifest, so one bad coordinate in one hole's reference would reject
           an otherwise perfect 18-hole package and leave the wrist with no map
           at all. The projection is required and still is; the reference is a
           bonus and degrades to nothing. Same policy as WatchScene.LocalPoint
           and this file's tolerant `version` decode. */
        init(from decoder: Decoder) throws {
            let values = try decoder.container(keyedBy: CodingKeys.self)
            holeNumber = try values.decode(Int.self, forKey: .holeNumber)
            asset = try values.decode(String.self, forKey: .asset)
            width = try values.decode(Double.self, forKey: .width)
            height = try values.decode(Double.self, forKey: .height)
            spatialReference = try values.decode(WatchMapSpatialReference.self, forKey: .spatialReference)
            reference = try? values.decode(WatchHoleReference.self, forKey: .reference)
        }
    }

    /* The package version is a millisecond timestamp that has crossed a
       Capacitor bridge and a plist-typed transfer before it gets here, so it
       can honestly arrive as an integer, a whole double, or a string. Refusing
       the whole manifest over its spelling would strand a valid package. */
    enum CodingKeys: String, CodingKey { case courseKey, version, holes }

    init(courseKey: String, version: Int64, holes: [Hole]) {
        self.courseKey = courseKey
        self.version = version
        self.holes = holes
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        courseKey = try values.decode(String.self, forKey: .courseKey)
        holes = try values.decode([Hole].self, forKey: .holes)
        if let exact = try? values.decode(Int64.self, forKey: .version) {
            version = exact
        } else if let text = try? values.decode(String.self, forKey: .version), let parsed = Int64(text) {
            version = parsed
        } else if let approximate = try? values.decode(Double.self, forKey: .version),
                  approximate.isFinite, approximate == approximate.rounded(), abs(approximate) < 9.0e15 {
            version = Int64(approximate)
        } else {
            throw DecodingError.dataCorruptedError(forKey: .version, in: values, debugDescription: "version is not a whole number")
        }
    }

    func hole(_ number: Int) -> Hole? { holes.first { $0.holeNumber == number } }

    /* Asset and course names arrive over WatchConnectivity and become path
       components on disk, so they are checked against the exact vocabulary the
       generator produces rather than merely sanitised. */
    static func isValidAssetName(_ name: String) -> Bool {
        guard name.hasSuffix(".webp") || name.hasSuffix(".png") else { return false }
        guard let dot = name.lastIndex(of: ".") else { return false }
        let stem = name[name.startIndex..<dot]
        guard stem.first == "h" else { return false }
        let digits = stem.dropFirst()
        guard (1...2).contains(digits.count), digits.allSatisfy(\.isASCII), digits.allSatisfy(\.isNumber) else { return false }
        return (Int(digits) ?? 0) > 0
    }

    /* Mirrors functions/course-watch-maps.mjs's slug(): lowercase alphanumerics
       and hyphens only, which is also exactly what makes a safe directory name. */
    static func isValidCourseKey(_ key: String) -> Bool {
        guard (1...90).contains(key.count) else { return false }
        return key.allSatisfy { $0.isASCII && ($0.isLowercase && $0.isLetter || $0.isNumber || $0 == "-") }
    }

    var isUsable: Bool {
        guard Self.isValidCourseKey(courseKey), version > 0, !holes.isEmpty else { return false }
        return holes.allSatisfy { $0.holeNumber > 0 && Self.isValidAssetName($0.asset) && $0.spatialReference.isUsable }
    }
}

/* Framing lives in WatchMapCamera (ios/WatchBubbleEngine), not here.

 There was a `WatchMapFrame` in this file that fitted the whole baked image into
 the view. It was right for a hole nobody is standing on and wrong for playing
 one: a par 5 bakes to about 1:7.7 and a 42mm watch is 1:1.2, so containing the
 image drew Millbrook's 1st 28pt wide with 84% of the screen as black bars.

 WatchMapCamera.play fills the screen and shows the part being played, and it is
 in the package because it is pure — image pixels in, image pixels out, no view
 and no gesture — so it can be tested without a wrist. Deleted rather than left
 unused: an unreferenced framing helper beside a live one is exactly how the
 wrong one gets picked up again. */
