import CoreGraphics
import Foundation

/* The Watch half of the "lite map" contract baked by scripts/gd-watch-map-core.js.

 A lite map is one flat vector-drawn image per hole plus the spatial reference
 needed to put a GPS coordinate on it. Nothing here re-derives geometry: the
 phone never sends course objects to the wrist, only the baked image and the
 four transform coefficients the generator already committed to.

 The projection is a deliberate line-for-line mirror of the generator's
 worldPx/applyTransform/invertTransform. If these two ever disagree the marker
 lands in the wrong place with no error to show for it, so the maths is copied
 rather than approximated — and dev/watch-map-projection.test.js pins the same
 numbers on the JavaScript side.

 Everything is Double, never Float: a z20 world pixel is ~2.7e8 and the
 transform's translation terms are larger still, so single precision would lose
 metres of accuracy inside an image only a few hundred pixels wide. */
struct WatchMapSpatialReference: Codable, Equatable {
    static let supportedVersion = 1
    private static let tileSize: Double = 256
    private static let maxMercatorLatitude: Double = 85.05112878

    let version: Int
    let refZoom: Int
    let transform: Transform
    let imageWidth: Double
    let imageHeight: Double
    let rotationDegrees: Double?
    let metresPerPixel: Double?

    struct Transform: Codable, Equatable {
        let a: Double
        let b: Double
        let tx: Double
        let ty: Double
    }

    /* A package generated by a newer recipe, or one whose transform is
       degenerate, is unusable rather than approximately usable — the caller
       shows the numbers-only face instead of a map with drifting markers. */
    var isUsable: Bool {
        guard version == Self.supportedVersion else { return false }
        guard imageWidth > 0, imageHeight > 0 else { return false }
        guard transform.a.isFinite, transform.b.isFinite, transform.tx.isFinite, transform.ty.isFinite else { return false }
        return transform.a * transform.a + transform.b * transform.b > 0
    }

    /// Image-pixel position of a real-world coordinate. Nil when the reference
    /// is unusable or the coordinate itself is not finite.
    func imagePoint(lat: Double, lng: Double) -> CGPoint? {
        guard isUsable, lat.isFinite, lng.isFinite else { return nil }
        let world = Self.worldPixel(lat: lat, lng: lng, zoom: refZoom)
        let x = transform.a * world.x - transform.b * world.y + transform.tx
        let y = transform.b * world.x + transform.a * world.y + transform.ty
        guard x.isFinite, y.isFinite else { return nil }
        return CGPoint(x: x, y: y)
    }

    /// Inverse of `imagePoint` — only used for diagnostics today, but it is the
    /// half that proves the transform round-trips.
    func coordinate(atImageX x: Double, y: Double) -> (lat: Double, lng: Double)? {
        guard isUsable else { return nil }
        let determinant = transform.a * transform.a + transform.b * transform.b
        let sx = x - transform.tx
        let sy = y - transform.ty
        let worldX = (transform.a * sx + transform.b * sy) / determinant
        let worldY = (transform.a * sy - transform.b * sx) / determinant
        let scale = Self.tileSize * pow(2, Double(refZoom))
        let n = Double.pi * (1 - (2 * worldY) / scale)
        let lat = atan(sinh(n)) * 180 / Double.pi
        let lng = (worldX / scale) * 360 - 180
        guard lat.isFinite, lng.isFinite else { return nil }
        return (lat, lng)
    }

    private static func worldPixel(lat: Double, lng: Double, zoom: Int) -> CGPoint {
        let scale = tileSize * pow(2, Double(zoom))
        let clamped = min(max(lat, -maxMercatorLatitude), maxMercatorLatitude)
        let latRad = clamped * Double.pi / 180
        return CGPoint(
            x: ((lng + 180) / 360) * scale,
            y: ((1 - log(tan(latRad) + 1 / cos(latRad)) / Double.pi) / 2) * scale
        )
    }
}

/* One course's package as the phone describes it. `version` is the generator's
   millisecond package version; it is the whole cache key, because a regenerated
   package lands under a new version folder and never overwrites the old one. */
struct WatchMapManifest: Codable, Equatable {
    let courseKey: String
    let version: Int64
    let holes: [Hole]

    struct Hole: Codable, Equatable {
        let holeNumber: Int
        let asset: String
        let width: Double
        let height: Double
        let spatialReference: WatchMapSpatialReference
    }

    /* The package version is a millisecond timestamp that has crossed a
       Capacitor bridge and a plist-typed transfer before it gets here, so it
       can honestly arrive as an integer, a whole double, or a string. Refusing
       the whole manifest over its spelling would strand a valid package. */
    enum CodingKeys: String, CodingKey { case courseKey, version, holes }

    init(courseKey: String, version: Int64, holes: [Hole]) {
        self.courseKey = courseKey
        self.version = version
        self.holes = holes
    }

    init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: CodingKeys.self)
        courseKey = try values.decode(String.self, forKey: .courseKey)
        holes = try values.decode([Hole].self, forKey: .holes)
        if let exact = try? values.decode(Int64.self, forKey: .version) {
            version = exact
        } else if let text = try? values.decode(String.self, forKey: .version), let parsed = Int64(text) {
            version = parsed
        } else if let approximate = try? values.decode(Double.self, forKey: .version),
                  approximate.isFinite, approximate == approximate.rounded(), abs(approximate) < 9.0e15 {
            version = Int64(approximate)
        } else {
            throw DecodingError.dataCorruptedError(forKey: .version, in: values, debugDescription: "version is not a whole number")
        }
    }

    func hole(_ number: Int) -> Hole? { holes.first { $0.holeNumber == number } }

    /* Asset and course names arrive over WatchConnectivity and become path
       components on disk, so they are checked against the exact vocabulary the
       generator produces rather than merely sanitised. */
    static func isValidAssetName(_ name: String) -> Bool {
        guard name.hasSuffix(".webp") || name.hasSuffix(".png") else { return false }
        guard let dot = name.lastIndex(of: ".") else { return false }
        let stem = name[name.startIndex..<dot]
        guard stem.first == "h" else { return false }
        let digits = stem.dropFirst()
        guard (1...2).contains(digits.count), digits.allSatisfy(\.isASCII), digits.allSatisfy(\.isNumber) else { return false }
        return (Int(digits) ?? 0) > 0
    }

    /* Mirrors functions/course-watch-maps.mjs's slug(): lowercase alphanumerics
       and hyphens only, which is also exactly what makes a safe directory name. */
    static func isValidCourseKey(_ key: String) -> Bool {
        guard (1...90).contains(key.count) else { return false }
        return key.allSatisfy { $0.isASCII && ($0.isLowercase && $0.isLetter || $0.isNumber || $0 == "-") }
    }

    var isUsable: Bool {
        guard Self.isValidCourseKey(courseKey), version > 0, !holes.isEmpty else { return false }
        return holes.allSatisfy { $0.holeNumber > 0 && Self.isValidAssetName($0.asset) && $0.spatialReference.isUsable }
    }
}

/* Where the scaled image sits inside the view, and how to put an image pixel on
   screen. It lives beside the projection rather than inside the view because it
   is the other half of "is this marker in the right place": the transform says
   which pixel, this says where that pixel is on a 176pt-wide screen. Pure
   CoreGraphics, so it can be exercised without a running Watch. */
struct WatchMapFrame {
    /// Never magnify a 448px-wide bake past this, or the flat vector edges turn
    /// to mush and the map reads as broken rather than close-up.
    private static let maximumScale: CGFloat = 3

    let scale: CGFloat
    let origin: CGPoint

    init(imageSize: CGSize, viewSize: CGSize, interest: [CGPoint]) {
        guard imageSize.width > 0, imageSize.height > 0, viewSize.width > 0, viewSize.height > 0 else {
            scale = 1
            origin = .zero
            return
        }
        let fitScale = min(viewSize.width / imageSize.width, viewSize.height / imageSize.height)
        var chosen = fitScale
        var focus = CGPoint(x: imageSize.width / 2, y: imageSize.height / 2)

        if interest.count >= 2 {
            let xs = interest.map(\.x), ys = interest.map(\.y)
            let minX = xs.min()!, maxX = xs.max()!, minY = ys.min()!, maxY = ys.max()!
            /* Padding is proportional so a 20m chip and a 500m par 5 both get
               breathing room, with a floor so the markers never touch the bezel. */
            let padding = max(24, 0.22 * max(maxX - minX, maxY - minY))
            let boxWidth = (maxX - minX) + padding * 2
            let boxHeight = (maxY - minY) + padding * 2
            chosen = min(viewSize.width / boxWidth, viewSize.height / boxHeight)
            chosen = min(max(chosen, fitScale), Self.maximumScale)
            focus = CGPoint(x: (minX + maxX) / 2, y: (minY + maxY) / 2)
        } else if let only = interest.first {
            chosen = min(max(fitScale, 1.4), Self.maximumScale)
            focus = only
        }

        scale = chosen
        let scaled = CGSize(width: imageSize.width * chosen, height: imageSize.height * chosen)
        origin = CGPoint(
            x: Self.axisOrigin(scaledLength: scaled.width, viewLength: viewSize.width, focus: focus.x * chosen),
            y: Self.axisOrigin(scaledLength: scaled.height, viewLength: viewSize.height, focus: focus.y * chosen)
        )
    }

    func place(_ imagePoint: CGPoint) -> CGPoint {
        CGPoint(x: origin.x + imagePoint.x * scale, y: origin.y + imagePoint.y * scale)
    }

    /* Centre on the focus, then refuse to show background past an edge — an
       off-centre hole is better than a map that appears to float. */
    private static func axisOrigin(scaledLength: CGFloat, viewLength: CGFloat, focus: CGFloat) -> CGFloat {
        guard scaledLength > viewLength else { return (viewLength - scaledLength) / 2 }
        return min(0, max(viewLength - scaledLength, viewLength / 2 - focus))
    }
}
