import Foundation

/* The arithmetic and geography the Bubble engine is built on, ported to match
 the JavaScript engine's behaviour rather than Swift's conventions.

 Every function here is a deliberate copy of one in app/js/bubble-engine.js —
 which is itself generated byte-for-byte from scripts/gd-app-core.js — and the
 differences between the two languages are the whole reason this file is
 separate and commented. Getting `round` or `bearing` subtly wrong would not
 crash anything; it would move a Bubble by a metre and put the two engines
 quietly out of step, which is the exact failure the parity fixtures exist to
 catch. */
enum JS {

    /* JavaScript's Math.round is NOT Swift's rounded().

       Math.round rounds halves toward POSITIVE INFINITY: Math.round(-0.5) is 0,
       and Math.round(-1.5) is -1. Swift's `.rounded()` rounds halves away from
       zero, giving -1 and -2. The difference only shows on an exact .5, which
       is rare — and it lands squarely on left-handed players, whose cluster
       tilt is the negation of a right-hander's and therefore hits negative
       halves that a right-hander never does.

       `floor(x + 0.5)` is Math.round exactly. */
    static func round(_ value: Double) -> Double {
        guard value.isFinite else { return 0 }
        return (value + 0.5).rounded(.down)
    }

    /// `gdRound(value, decimals)` — Math.round(v * 10^d) / 10^d, non-finite to 0.
    static func round(_ value: Double, _ decimals: Int) -> Double {
        let p = pow(10.0, Double(decimals))
        return round((value.isFinite ? value : 0) * p) / p
    }

    /// `gdClamp` — note it coerces non-finite to 0 BEFORE clamping, exactly as
    /// `Number(value)||0` does, so a NaN lands on 0 and not on a bound.
    static func clamp(_ value: Double, _ minimum: Double, _ maximum: Double) -> Double {
        Swift.max(minimum, Swift.min(maximum, value.isFinite ? value : 0))
    }

    /// `gdFiniteNumber(value, fallback)`.
    static func finite(_ value: Double?, _ fallback: Double) -> Double {
        guard let value, value.isFinite else { return fallback }
        return value
    }

    /// `gdHandednessSign` — anything that is not exactly "left" is right-handed.
    static func handednessSign(_ handedness: WatchBubbleProfile.Handedness) -> Double { handedness.sign }

    static func normAng(_ angle: Double) -> Double {
        var a = angle
        while a <= -Double.pi { a += Double.pi * 2 }
        while a > Double.pi { a -= Double.pi * 2 }
        return a
    }
}

/* Geography, in the two flavours the engine deliberately uses for different
 jobs. They disagree, and the disagreement is load-bearing. */
enum Geo {

    /// The engine's own flat-earth metres-per-degree, used by `project`.
    static let metresPerDegree: Double = 111_320

    /// The radius `map.distance` uses — app/js/distance.js's haversine, which
    /// is what Leaflet's own `map.distance` computes.
    static let earthRadiusM: Double = 6_371_008.8

    /* `bearing(a, b)` — atan2(dLng, dLat), with NO cosine correction.

       This is not an oversight to be corrected here. It is the bearing the
       phone's engine uses to lay every Bubble down, and it is paired with
       `project` below, which DOES apply the cosine. Adding the correction here
       would produce a "more correct" bearing that disagrees with the phone by a
       fraction of a degree at every latitude away from the equator — visible as
       a Bubble rotated slightly differently on the two screens, with nothing to
       say why. Faithfulness beats correctness at a boundary like this one; if
       the convention is ever wrong it should be changed in gd-app-core.js and
       land on both surfaces together. */
    static func bearing(_ a: Coordinate, _ b: Coordinate) -> Double {
        atan2(b.lng - a.lng, b.lat - a.lat)
    }

    /// `project(origin, angle, metres)` — flat-earth, cosine-corrected in
    /// longitude at the ORIGIN's latitude.
    static func project(_ origin: Coordinate, _ angle: Double, _ metres: Double) -> Coordinate {
        Coordinate(
            lat: origin.lat + (cos(angle) * metres) / metresPerDegree,
            lng: origin.lng + (sin(angle) * metres) / (metresPerDegree * cos(origin.lat * Double.pi / 180))
        )
    }

    /* `projectOffset(origin, angle, forward, side)` — forward along the shot,
       then square to it. The second step re-derives the cosine at the FORWARD
       point's latitude rather than the origin's, which is what the JavaScript
       does and is not the same as offsetting once from the origin. */
    static func projectOffset(_ origin: Coordinate, _ angle: Double, _ forward: Double, _ side: Double) -> Coordinate {
        let p = project(origin, angle, forward)
        let perpendicular = angle + Double.pi / 2
        return Coordinate(
            lat: p.lat + (cos(perpendicular) * side) / metresPerDegree,
            lng: p.lng + (sin(perpendicular) * side) / (metresPerDegree * cos(p.lat * Double.pi / 180))
        )
    }

    /// `map.distance` — the haversine from app/js/distance.js. Used for every
    /// distance the engine measures; `project` above is used to place points.
    static func distance(_ a: Coordinate, _ b: Coordinate) -> Double {
        let dLat = (b.lat - a.lat) * Double.pi / 180
        let dLng = (b.lng - a.lng) * Double.pi / 180
        let h = sin(dLat / 2) * sin(dLat / 2)
            + cos(a.lat * Double.pi / 180) * cos(b.lat * Double.pi / 180) * sin(dLng / 2) * sin(dLng / 2)
        return 2 * earthRadiusM * asin(min(1, h.squareRoot()))
    }

    /// `localPointToLatLng` — a point in the shot's own frame, placed on the map.
    static func localPointToLatLng(_ centre: Coordinate, _ shotBearing: Double, _ x: Double, _ y: Double) -> Coordinate {
        project(centre, shotBearing + atan2(y, x), (x * x + y * y).squareRoot())
    }
}
