using Toybox.Lang;
using Toybox.Math;

// The arithmetic and geography the Bubble engine is built on. A deliberate
// copy of ios/WatchBubbleEngine/Sources/WatchBubbleEngine/BubbleMath.swift,
// which is itself a port of app/js/bubble-engine.js (generated byte-for-byte
// from scripts/gd-app-core.js). Getting `round` or `bearing` subtly wrong
// would not crash anything — it would move a Bubble by a metre and put the
// engines quietly out of step, which is exactly what the parity fixtures
// (dev/fixtures/bubble-engine-parity.json) exist to catch. Faithfulness beats
// idiom here throughout.

module GarminJS {

    // JavaScript's Math.round rounds halves toward POSITIVE INFINITY:
    // Math.round(-0.5) is 0, Math.round(-1.5) is -1. Monkey C's Math.round
    // (like Swift's .rounded()) rounds halves away from zero. floor(x + 0.5)
    // is Math.round exactly, and is what this must use everywhere the phone
    // rounds a value that might be exactly on a half.
    function round(value) {
        if (value == null || !(value instanceof Lang.Float or value instanceof Lang.Double or value instanceof Lang.Number)) {
            return 0.0;
        }
        return Math.floor(value.toDouble() + 0.5);
    }

    // gdRound(value, decimals) — Math.round(v * 10^d) / 10^d.
    function roundTo(value, decimals) {
        var p = Math.pow(10.0, decimals);
        var v = (value != null) ? value.toDouble() : 0.0;
        return round(v * p) / p;
    }

    // gdClamp — coerces non-finite to 0 BEFORE clamping.
    function clamp(value, minimum, maximum) {
        var v = (value != null) ? value.toDouble() : 0.0;
        if (v < minimum) { return minimum; }
        if (v > maximum) { return maximum; }
        return v;
    }

    function finiteOr(value, fallback) {
        if (value == null) { return fallback; }
        return value.toDouble();
    }

    function normAng(angle) {
        var a = angle;
        while (a <= -Math.PI) { a += Math.PI * 2; }
        while (a > Math.PI) { a -= Math.PI * 2; }
        return a;
    }
}

// Geography, in the two flavours the engine deliberately uses for different
// jobs. They disagree, and the disagreement is load-bearing — see
// `bearing()` below.
module GarminGeo {

    // The engine's own flat-earth metres-per-degree, used by `project`.
    var METRES_PER_DEGREE = 111320.0;

    // The radius `map.distance` uses — app/js/distance.js's haversine.
    var EARTH_RADIUS_M = 6371008.8;

    function degToRad(deg) {
        return deg * Math.PI / 180.0;
    }
    function radToDeg(rad) {
        return rad * 180.0 / Math.PI;
    }

    // bearing(a, b) — atan2(dLng, dLat), with NO cosine correction. This is
    // not an oversight: it is the bearing the phone's engine uses to lay
    // every Bubble down, paired with `project()` below which DOES apply the
    // cosine. "Correcting" it here would rotate the Garmin Bubble a fraction
    // of a degree away from the phone's at every latitude off the equator,
    // for no visible reason. If the convention is ever wrong, it must change
    // in scripts/gd-app-core.js and land on every surface together.
    function bearing(a, b) {
        return Math.atan2(b.lng - a.lng, b.lat - a.lat);
    }

    // project(origin, angle, metres) — flat-earth, cosine-corrected in
    // longitude at the ORIGIN's latitude.
    function project(origin, angle, metres) {
        var lat = origin.lat + (Math.cos(angle) * metres) / METRES_PER_DEGREE;
        var lng = origin.lng + (Math.sin(angle) * metres) / (METRES_PER_DEGREE * Math.cos(degToRad(origin.lat)));
        return new GarminCoordinate(lat, lng);
    }

    // projectOffset(origin, angle, forward, side) — forward along the shot,
    // then square to it. The perpendicular step re-derives the cosine at the
    // FORWARD point's latitude, not the origin's — not the same as offsetting
    // once from the origin, and must match exactly.
    function projectOffset(origin, angle, forward, side) {
        var p = project(origin, angle, forward);
        var perpendicular = angle + Math.PI / 2.0;
        var lat = p.lat + (Math.cos(perpendicular) * side) / METRES_PER_DEGREE;
        var lng = p.lng + (Math.sin(perpendicular) * side) / (METRES_PER_DEGREE * Math.cos(degToRad(p.lat)));
        return new GarminCoordinate(lat, lng);
    }

    // map.distance — the haversine from app/js/distance.js. Used for every
    // distance the engine measures; `project` above is used to place points.
    function distance(a, b) {
        var dLat = degToRad(b.lat - a.lat);
        var dLng = degToRad(b.lng - a.lng);
        var h = Math.sin(dLat / 2.0) * Math.sin(dLat / 2.0)
            + Math.cos(degToRad(a.lat)) * Math.cos(degToRad(b.lat)) * Math.sin(dLng / 2.0) * Math.sin(dLng / 2.0);
        var root = h > 0 ? Math.sqrt(h) : 0.0;
        if (root > 1.0) { root = 1.0; }
        return 2.0 * EARTH_RADIUS_M * Math.asin(root);
    }

    // localPointToLatLng — a point in the shot's own frame, placed on the map.
    function localPointToLatLng(centre, shotBearing, x, y) {
        var mag = Math.sqrt(x * x + y * y);
        return project(centre, shotBearing + Math.atan2(y, x), mag);
    }
}
