/* GENERATED by dev/generate-bubble-engine-client.js — DO NOT HAND-EDIT.
   Every function in the VERBATIM sections below is a byte-for-byte copy from
   gd-app-core.js / gd-course-library-pin-lock.js, asserted identical by
   dev/fresh-app-boot.test.js. Change the engine, then re-run the generator. */
(function () {
  "use strict";

/* ==== VERBATIM consts (gd-app-core.js) ==== */
const GD_DEFAULT_CLUB_CARRY_M={Driver:230,"3W":205,"4H":180,"4i":178,"5i":170,"6i":160,"7i":155,"8i":142,"9i":130,PW:115,GW:98,SW:82,LW:66};
const GD_CLUB_GROUPS={driver:/driver/i,woodHybrid:/3w|wood|hybrid|4h/i,wedge:/pw|gw|sw|lw|wedge/i};
const GD_BAG_FIRMNESS_PRESETS={soft:{label:"Soft",multiplier:.45},medium:{label:"Medium",multiplier:1},hard:{label:"Hard",multiplier:1.65}};
const GD_CLUB_PATTERN_RATIOS={driver:{width:.19,depth:.23,carryWindowPct:5.4,faceWindowDeg:.95,tiltBaseDeg:5},woodHybrid:{width:.17,depth:.215,carryWindowPct:4.9,faceWindowDeg:.85,tiltBaseDeg:4.5},iron:{width:.148,depth:.195,carryWindowPct:4.2,faceWindowDeg:.7,tiltBaseDeg:4},wedge:{width:.12,depth:.16,carryWindowPct:3.4,faceWindowDeg:.55,tiltBaseDeg:2.5}};
const GD_BAG_FIRMNESS_KEY="gd_bag_total_firmness_v1";
const PLACEHOLDER_PLAYER_PROFILE={
  source:"placeholder-profile",
  playerId:"placeholder-v24",
  handedness:"right",
  // Clean app input for now: no user-facing face/path controls here.
  // This represents face relative to ACTUAL alignment line, not face-to-path.
  baseCalibration:{club:"7i",baseCarry:155,faceAlignmentOffsetDeg:1.4,faceWindowDeg:.7,faceToPathToleranceDeg:.7,carryWindowPct:4.2,dispersionMultiplier:1,gdbTrust:1},
  // Internal-only fallback used when GPS needs a safe generic bubble without showing bag placeholders.
  standInBag:gdDefaultStandInBag()
};

/* ==== VERBATIM functions (gd-app-core.js) ==== */
function gdClamp(value,min,max){return Math.max(min,Math.min(max,Number(value)||0))}
function gdRound(value,decimals=2){const p=Math.pow(10,decimals);return Math.round((Number(value)||0)*p)/p}
function gdFiniteNumber(value,fallback=null){const n=Number(value);return Number.isFinite(n)?n:fallback}
function gdHandednessSign(handedness="right"){return handedness==="left"?-1:1}
function normAng(a){
  while(a<=-Math.PI)a+=Math.PI*2;
  while(a>Math.PI)a-=Math.PI*2;
  return a;
}
function bearing(a,b){return Math.atan2(b.lng-a.lng,b.lat-a.lat)}
function project(o,a,m){const earth=111320;return L.latLng(o.lat+(Math.cos(a)*m)/earth,o.lng+(Math.sin(a)*m)/(earth*Math.cos(o.lat*Math.PI/180)))}
function projectOffset(o,a,f,s){const p=project(o,a,f),perp=a+Math.PI/2,earth=111320;return L.latLng(p.lat+(Math.cos(perp)*s)/earth,p.lng+(Math.sin(perp)*s)/(earth*Math.cos(p.lat*Math.PI/180)))}
function gdBagFirmness(){try{const stored=localStorage.getItem(GD_BAG_FIRMNESS_KEY);if(GD_BAG_FIRMNESS_PRESETS[stored])return stored}catch(e){}return"medium"}
function gdBagFirmnessMultiplier(preset=gdBagFirmness()){return GD_BAG_FIRMNESS_PRESETS[preset]?.multiplier??1}
function gdRolloutBasePct(club="7i"){
  const group=gdGetClubGroup(club);
  const fallback={driver:.11,woodHybrid:.095,iron:.075,wedge:.047}[group]||.075;
  try{
    if(group==="driver")return gdFiniteNumber(dev("clubScaling.driverRolloutPct"),fallback);
    if(group==="woodHybrid")return gdFiniteNumber(dev("clubScaling.ironRolloutPct"),.075)*1.35;
    if(group==="wedge")return gdFiniteNumber(dev("clubScaling.wedgeRolloutPct"),fallback);
    return gdFiniteNumber(dev("clubScaling.ironRolloutPct"),fallback);
  }catch(e){return fallback}
}
function gdBagTotalForCarry(club,carry,preset=gdBagFirmness()){
  const c=Math.max(0,Math.round(Number(carry)||0));
  if(!c)return 0;
  const pct=Math.max(0,gdRolloutBasePct(club)*gdBagFirmnessMultiplier(preset));
  return Math.max(c,Math.round(c*(1+pct)));
}
function gdCarryM(row){return Math.round(Number(row?.baseCarry??row?.carry??row?.distance??row?.meters)||0)}
function gdTotalM(row){
  const carry=gdCarryM(row);
  const saved=Math.round(Number(row?.totalM??row?.total??row?.totalDistance??row?.baseTotal)||0);
  return saved>=carry&&saved>0?saved:gdBagTotalForCarry(row?.club||row?.name,carry);
}
function gdDefaultStandInBag(){return Object.entries(GD_DEFAULT_CLUB_CARRY_M).map(([club,baseCarry])=>({club,baseCarry,totalM:gdBagTotalForCarry(club,baseCarry)}))}
function gdShotActiveProfile(){
  try{
    const api=window.GolfDaddyAccounts||window.ClarityCaddieAccounts;
    const account=api&&typeof api.current==="function"?api.current():null;
    if(account){
      let profile=null;
      try{profile=typeof gdActiveAccountProfile==="function"?gdActiveAccountProfile(account):null;}catch(e){}
      if(!profile&&account.profileId&&typeof gdProfileById==="function")profile=gdProfileById(account.profileId);
      if(profile&&!profile.placeholderProfile)return profile;
    }
  }catch(e){}
  try{
    const p=activePlayerProfile&&activePlayerProfile();
    if(p&&!p.placeholderProfile)return p;
  }catch(e){}
  return null;
}
function gdNormaliseBagRow(c){const club=String(c?.club||c?.name||'').trim();const baseCarry=Math.round(Number(c?.baseCarry??c?.carry??c?.distance??c?.meters)||0);if(!club||baseCarry<=0)return null;const totalM=Math.max(baseCarry,gdTotalM({...c,club,baseCarry}));return{club,baseCarry,totalM}}
function gdNormaliseShotBagRows(rows){
  return (Array.isArray(rows)?rows:[]).map(row=>gdNormaliseBagRow(row)).filter(row=>row&&String(row.club||"").trim()&&gdCarryM(row)>0).sort((a,b)=>gdTotalM(b)-gdTotalM(a));
}
function gdAccountShotBagRows(){
  const p=gdShotActiveProfile();
  if(!p||p.placeholderProfile||p.bagSeededDefault||!Array.isArray(p.bag))return [];
  return gdNormaliseShotBagRows(p.bag);
}
function gdGhostShotBagRows(){
  return gdNormaliseShotBagRows(gdDefaultStandInBag()).map(row=>({...row,ghostBag:true}));
}
function gdPlayableShotBagRows(){
  const accountRows=gdAccountShotBagRows();
  return accountRows.length?accountRows:gdGhostShotBagRows();
}
function gdActiveShotBagRows(){
  try{return gdAccountShotBagRows();}catch(e){return []}
}
function gdHasPlayableBag(){
  try{return gdPlayableShotBagRows().length>0;}catch(e){return false}
}
function gdResolveShotBagClub(rows,club="Bag",distance=155){
  const bag=gdNormaliseShotBagRows(rows);
  if(!bag.length)return null;
  const wanted=String(club||"").trim().toLowerCase();
  if(wanted&&wanted!=="bag"){
    const exact=bag.find(row=>String(row.club||"").trim().toLowerCase()===wanted);
    if(exact)return exact;
  }
  const d=Math.max(1,Number(distance)||155);
  return bag.reduce((best,row)=>Math.abs(gdTotalM(row)-d)<Math.abs(gdTotalM(best)-d)?row:best,bag.find(row=>String(row.club).toLowerCase()==="7i")||bag[0]);
}
function gdMaxPlayableCarryM(){
  try{
    const totals=gdPlayableShotBagRows().map(gdTotalM).filter(n=>Number.isFinite(n)&&n>0);
    return totals.length?Math.max(...totals):null;
  }catch(e){return null}
}
function gdTargetForGreenCentre(center,opts={}){
  if(typeof gdTournamentModeEnabled==="function"&&gdTournamentModeEnabled())return center;
  if(!start||!center)return center;
  const maxCarry=gdMaxPlayableCarryM();
  if(!(maxCarry>0))return center;
  const d=map.distance(start,center);
  if(d<=maxCarry+3)return center;
  try{
    const fairwayTarget=gdFairwayLineGrabAllowed()&&typeof window.gdMappedFairwayLayupTarget==="function"?window.gdMappedFairwayLayupTarget(start,center,maxCarry,{hole:opts.hole||gdMappedStartHoleNumber?.()}):null;
    if(fairwayTarget)return fairwayTarget;
  }catch(e){}
  return project(start,bearing(start,center),maxCarry);
}
function gdStartIsInMappedTeeArea(radiusM=78){
  if(!start||!map)return false;
  try{
    const tee=typeof gdActiveMappedTeeStartPoint==="function"?gdActiveMappedTeeStartPoint():null;
    if(!tee)return false;
    const d=map.distance(start,tee);
    return Number.isFinite(d)&&d<=Math.max(25,Number(radiusM)||78);
  }catch(e){return false}
}
function gdFairwayLineGrabAllowed(opts={}){
  if(!start||!map)return false;
  try{
    if(document.body&&document.body.classList.contains("gdHeadToTeeFrameActive"))return gdStartIsInMappedTeeArea(opts.radiusM||110);
  }catch(e){}
  return gdStartIsInMappedTeeArea(opts.radiusM||78);
}
function gdNormAngle(a){
  const full=Math.PI*2;
  return ((Number(a)||0)%full+full)%full;
}
function gdWindEffectMeters(aimPoint=target){
  const basis=start&&aimPoint?map.distance(start,aimPoint):(start&&greenCentre?map.distance(start,greenCentre):140);
  const carry=Math.max(40,Math.min(260,Number(basis)||140));
  const base=Math.max(4,Math.min(12,carry*.045));
  return base*Math.max(1,Math.min(3,Number(gdWindLevel)||1));
}
function gdWindLandingFromAim(aimPoint){
  if(!aimPoint||!gdHasWindVector())return aimPoint||null;
  return project(aimPoint,gdNormAngle(gdWindOriginAngle+Math.PI),gdWindEffectMeters(aimPoint));
}
function gdSyncWindLandingFromAim(){
  if(!gdHasWindVector()||!target){gdWindLandingTarget=null;return null;}
  gdWindLandingTarget=gdWindLandingFromAim(target);
  return gdWindLandingTarget;
}
function gdGetClubGroup(club="7i"){if(GD_CLUB_GROUPS.driver.test(club))return"driver";if(GD_CLUB_GROUPS.woodHybrid.test(club))return"woodHybrid";if(GD_CLUB_GROUPS.wedge.test(club))return"wedge";return"iron"}
function gdDefaultCarryForClub(club="7i"){return GD_DEFAULT_CLUB_CARRY_M[club]??155}
function gdGetClubPatternDefaults(club="7i"){return GD_CLUB_PATTERN_RATIOS[gdGetClubGroup(club)]}
function gdBubbleGeometryTuning(){
  const get=path=>{try{return typeof dev==="function"?Number(dev(path)):NaN;}catch(e){return NaN;}};
  const num=(value,fallback)=>Number.isFinite(value)?value:fallback;
  return{
    widthScale:gdClamp(num(get("bubbleGeometry.widthScale"),1),.3,2.5),
    depthScale:gdClamp(num(get("bubbleGeometry.depthScale"),1),.3,2.5),
    tiltScale:gdClamp(num(get("bubbleGeometry.tiltScale"),1),0,3),
    tiltMaxDeg:gdClamp(num(get("bubbleGeometry.tiltMaxDeg"),14),1,25),
    gpsMaxLateralPct:gdClamp(num(get("bubbleGeometry.gpsMaxLateralPct"),.13),.03,.5),
    gpsMaxDepthPct:gdClamp(num(get("bubbleGeometry.gpsMaxDepthPct"),.18),.04,.6),
    gpsMaxLateralM:gdClamp(num(get("bubbleGeometry.gpsMaxLateralM"),28),8,120),
    gpsMaxDepthM:gdClamp(num(get("bubbleGeometry.gpsMaxDepthM"),38),10,150),
    gpsPixelCapScale:gdClamp(num(get("bubbleGeometry.gpsPixelCapScale"),1),.3,3)
  };
}
function gdResolveFaceAlignmentOffsetDeg(input={}){return Number(input.faceAlignmentOffsetDeg??input.faceOffsetDeg??0)}
function gdDeriveAimOffset({faceAlignmentOffsetDeg=0,baseCarry=155}){const deg=Number(faceAlignmentOffsetDeg)||0, carry=Number(baseCarry)||155;return{aimOffsetDeg:gdRound(deg,2),aimOffsetM:gdRound(Math.tan((deg*Math.PI)/180)*carry,2)}}
function gdDeriveBasePatternSize({club="7i",baseCarry=gdDefaultCarryForClub(club),dispersionMultiplier=1}){const carry=Number(baseCarry)||gdDefaultCarryForClub(club), ratios=gdGetClubPatternDefaults(club), m=gdClamp(dispersionMultiplier,.6,1.8), geo=gdBubbleGeometryTuning();return{clusterWidthM:gdRound(carry*ratios.width*m*geo.widthScale,1),clusterDepthM:gdRound(carry*ratios.depth*m*geo.depthScale,1),dispersionMultiplier:gdRound(m,2)}}
function gdDeriveDistanceTendency({faceDeltaFromPatternDeg=0,handedness="right",club="7i"}){const hand=gdHandednessSign(handedness), openSide=hand*(Number(faceDeltaFromPatternDeg)||0), group=gdGetClubGroup(club), strength={driver:.42,woodHybrid:.36,iron:.30,wedge:.18}[group];return gdRound(gdClamp(-openSide*strength,-5,5),2)}
function gdDerivePatternWindow({club="7i",faceWindowDeg,carryWindowPct}){const defaults=gdGetClubPatternDefaults(club);return{faceWindowDeg:gdRound(Number(faceWindowDeg??defaults.faceWindowDeg),2),carryWindowPct:gdRound(Number(carryWindowPct??defaults.carryWindowPct),2)}}
function gdDeriveClusterTilt({faceAlignmentOffsetDeg=0,faceWindowDeg=.7,carryWindowPct=4.2,handedness="right",club="7i"}){const hand=gdHandednessSign(handedness), defaults=gdGetClubPatternDefaults(club), geo=gdBubbleGeometryTuning(), offsetInfluence=Math.abs(Number(faceAlignmentOffsetDeg)||0)*.12, windowInfluence=Math.abs(Number(faceWindowDeg)||0)*.9, carryInfluence=Math.abs(Number(carryWindowPct)||0)*.08;return gdRound(gdClamp(hand*(defaults.tiltBaseDeg+offsetInfluence+windowInfluence+carryInfluence)*geo.tiltScale,-geo.tiltMaxDeg,geo.tiltMaxDeg),2)}
function calculateBubbleProfile(input={}){const club=input.club||"7i", baseCarry=Number(input.baseCarry??gdDefaultCarryForClub(club)), handedness=input.handedness||"right", faceAlignmentOffsetDeg=gdResolveFaceAlignmentOffsetDeg(input), dispersionMultiplier=Number(input.dispersionMultiplier??1), window=gdDerivePatternWindow({club,faceWindowDeg:input.faceWindowDeg,carryWindowPct:input.carryWindowPct}), size=gdDeriveBasePatternSize({club,baseCarry,dispersionMultiplier}), aim=gdDeriveAimOffset({faceAlignmentOffsetDeg,baseCarry}), distanceTendencyPct=gdDeriveDistanceTendency({faceDeltaFromPatternDeg:window.faceWindowDeg,handedness,club}), clusterTiltDeg=gdDeriveClusterTilt({faceAlignmentOffsetDeg,faceWindowDeg:window.faceWindowDeg,carryWindowPct:window.carryWindowPct,handedness,club});return{club,baseCarry:gdRound(baseCarry,1),totalM:Number.isFinite(Number(input.totalM))?gdRound(Number(input.totalM),1):null,faceAlignmentOffsetDeg:gdRound(faceAlignmentOffsetDeg,2),faceOffsetDeg:gdRound(faceAlignmentOffsetDeg,2),aimOffsetDeg:aim.aimOffsetDeg,aimOffsetM:aim.aimOffsetM,clusterWidthM:size.clusterWidthM,clusterDepthM:size.clusterDepthM,clusterTiltDeg,faceWindowDeg:window.faceWindowDeg,faceToPathToleranceDeg:gdRound(Number(input.faceToPathToleranceDeg??window.faceWindowDeg),2),carryWindowPct:window.carryWindowPct,distanceTendencyPct,dispersionMultiplier:size.dispersionMultiplier,gdbTrust:gdRound(Number(input.gdbTrust??1),2),faceToPathDeg:Number.isFinite(Number(input.faceToPathDeg))?gdRound(Number(input.faceToPathDeg),2):null,derivedAoADeg:Number.isFinite(Number(input.derivedAoADeg))?gdRound(Number(input.derivedAoADeg),2):null,impactStatus:"Baseline",shapeSource:"engine-derived",modelNote:"Offset places the shot data. Club/carry sizes it. Accepted delivery window shapes the tilt/depth realism."}}
function gdProfileInputForClub(club,distance){
  const bag=gdPlayableShotBagRows();
  const base=PLACEHOLDER_PLAYER_PROFILE.baseCalibration, c=gdResolveShotBagClub(bag,club,distance)||gdNearestStandInClub(distance);
  let offset=Number(base.faceAlignmentOffsetDeg??base.faceOffsetDeg??1.4);
  try{const p=gdShotActiveProfile();offset=gdProfileCentralOffset(p,offset)}catch(e){}
  return{...base,club:c.club,baseCarry:c.baseCarry,totalM:gdTotalM(c),handedness:PLACEHOLDER_PLAYER_PROFILE.handedness,faceAlignmentOffsetDeg:offset,faceOffsetDeg:offset}
}
function gdNearestStandInClub(distance){return gdResolveShotBagClub(gdGhostShotBagRows(),"Bag",distance)||{club:"7i",baseCarry:155,totalM:gdBagTotalForCarry("7i",155)}}
function gdProfileCentralOffset(p,fallback=1.4){const n=Number(p?.faceOffsetDeg??p?.centralFaceOffsetDeg??fallback);return Number.isFinite(n)?n:fallback}
function getActiveBubbleProfile(club="Bag",distance=155){
  try{
    const p=gdShotActiveProfile();
    const accountRows=gdAccountShotBagRows();
    const realBag=accountRows.length>0;
    const row=gdResolveShotBagClub(realBag?accountRows:gdGhostShotBagRows(),club,distance);
    if(row){
      const requested=row.club||"7i";
      // THE GPS BUBBLE NEEDS TWO THINGS: A DEGREE VALUE AND A BAG.
      // Aim comes from My Bubble's offset; size comes from the bag carry through
      // the club ratios. The saved bubble's SHAPE is deliberately not used here -
      // it used to be spread into the calibration, which meant a stored cluster
      // width/depth quietly resized the on-course bubble and made the played shape
      // depend on which key the bubble happened to be filed under.
      const offset=gdProfileCentralOffset(p,PLACEHOLDER_PLAYER_PROFILE.baseCalibration.faceAlignmentOffsetDeg);
      const base={...PLACEHOLDER_PLAYER_PROFILE.baseCalibration};
      const profile=calculateBubbleProfile({...base,club:requested,baseCarry:gdCarryM(row)||base.baseCarry,handedness:p?.handedness||PLACEHOLDER_PLAYER_PROFILE.handedness,skillLevel:p?.skillLevel||p?.consistency,faceOffsetDeg:offset,faceAlignmentOffsetDeg:offset,totalM:gdTotalM(row)});
      return{...profile,totalM:gdTotalM(row),source:realBag?"account-profile":"ghost-bag",playerId:p?.id||"",accountId:p?.accountId||"",ghostBag:!realBag}
    }
  }catch(e){}
  return calculateBubbleProfile(gdProfileInputForClub(club,distance));
}
function getGDBForClub(club,d){
  const profile=getActiveBubbleProfile(club,d);
  const carryM=Math.max(0,gdFiniteNumber(profile.baseCarry,0));
  const totalM=Math.max(carryM,gdFiniteNumber(profile.totalM,gdBagTotalForCarry(profile.club,carryM)));
  const rolloutM=Math.max(0,totalM-carryM);
  const baseVisual=calculateVisualBubbleRender(profile,{handedness:profile.handedness||PLACEHOLDER_PLAYER_PROFILE.handedness});
  const lateralRadius=Math.max(1,gdFiniteNumber(profile.clusterWidthM,baseVisual.visualWidthM)/2);
  const baseDepthRadius=Math.max(1,gdFiniteNumber(profile.clusterDepthM,baseVisual.visualDepthM)/2);
  const totalDepthRadius=rolloutM>0?Math.max(baseDepthRadius,rolloutM+Math.min(7,baseDepthRadius*.22)):baseDepthRadius;
  const visual={...baseVisual,visualDepthM:gdRound(Math.max(baseVisual.visualDepthM,totalDepthRadius*2),1)};
  const depthRadius=Math.max(totalDepthRadius,gdFiniteNumber(visual.visualDepthM,baseVisual.visualDepthM)/2);
  const radius=Math.max(dev("shotEngine.minimumBubbleRadiusM"),lateralRadius,depthRadius);
  return{...profile,totalM:gdRound(totalM,1),rolloutM:gdRound(rolloutM,1),visual,radius:gdRound(radius,1),lateralRadiusM:gdRound(lateralRadius,1),depthRadiusM:gdRound(depthRadius,1),source:profile.source||"account-profile",playerId:profile.playerId||"",accountId:profile.accountId||"",ghostBag:!!profile.ghostBag,engineAvailable:true}
}
function calculateVisualBubbleRender(profile,options={}){const handedness=options.handedness||"right", hand=gdHandednessSign(handedness), offsetNorm=gdClamp((hand*profile.faceAlignmentOffsetDeg)/6,-1,1), windowNorm=gdClamp((profile.faceWindowDeg||.7)/1.5,0,1), carryNorm=gdClamp((profile.carryWindowPct||4.2)/8,0,1);return{visualWidthM:gdRound(profile.clusterWidthM*(1+windowNorm*.1+Math.abs(offsetNorm)*.06),1),visualDepthM:gdRound(profile.clusterDepthM*(1+carryNorm*.08+windowNorm*.06),1),visualTiltDeg:gdRound(profile.clusterTiltDeg+offsetNorm*1.5+windowNorm*1.2,2),visualSkewDeg:gdRound(offsetNorm*5,2),visualYBias:gdRound(Math.max(0,offsetNorm)*.04-Math.max(0,-offsetNorm)*.03,3)}}
function gdNormalizeGpsBubblePayload(raw,distance=155){
  const fallback=gdFallbackGpsBubblePayload(distance);
  if(!raw||typeof raw!=="object")return fallback;
  const rawVisual=raw.visual&&typeof raw.visual==="object"?raw.visual:{};
  const visualWidthM=gdFiniteNumber(rawVisual.visualWidthM??raw.visualWidthM,gdFiniteNumber(raw.clusterWidthM,gdFiniteNumber(raw.lateralRadiusM,null)*2));
  const visualDepthM=gdFiniteNumber(rawVisual.visualDepthM??raw.visualDepthM,gdFiniteNumber(raw.clusterDepthM,gdFiniteNumber(raw.depthRadiusM,null)*2));
  if(!(visualWidthM>0)||!(visualDepthM>0))return fallback;
  const minRadius=Math.max(1,gdFiniteNumber(dev("shotEngine.minimumBubbleRadiusM"),7));
  const lateralRadiusM=Math.max(minRadius*.55,visualWidthM/2);
  const depthRadiusM=Math.max(minRadius*.55,visualDepthM/2);
  const radius=Math.max(minRadius,gdFiniteNumber(raw.radius,0),lateralRadiusM,depthRadiusM);
  return{
    ...fallback,
    ...raw,
    visual:{
      ...fallback.visual,
      ...rawVisual,
      visualWidthM:gdRound(visualWidthM,1),
      visualDepthM:gdRound(visualDepthM,1),
      visualTiltDeg:gdRound(gdClamp(gdFiniteNumber(rawVisual.visualTiltDeg,raw.clusterTiltDeg||0),-18,18),2),
      visualSkewDeg:gdRound(gdClamp(gdFiniteNumber(rawVisual.visualSkewDeg,0),-16,16),2),
      visualYBias:gdRound(gdClamp(gdFiniteNumber(rawVisual.visualYBias,0),-.18,.18),3)
    },
    radius:gdRound(radius,1),
    lateralRadiusM:gdRound(lateralRadiusM,1),
    depthRadiusM:gdRound(depthRadiusM,1),
    aimOffsetM:gdRound(gdFiniteNumber(raw.aimOffsetM,0),2),
    distanceTendencyPct:gdRound(gdClamp(gdFiniteNumber(raw.distanceTendencyPct,0),-10,10),2),
    shapeSource:raw.shapeSource||"engine-derived",
    engineAvailable:true
  };
}
function gdScaleGpsBubblePayloadForDisplay(payload,scale,reason="display-clamped"){
  const p=gdBubblePayloadForRender(payload);
  const visual=p.visual&&typeof p.visual==="object"?p.visual:{};
  const scaled={
    ...p,
    visual:{
      ...visual,
      visualWidthM:gdRound(Math.max(1,gdFiniteNumber(visual.visualWidthM,p.lateralRadiusM*2))*scale,1),
      visualDepthM:gdRound(Math.max(1,gdFiniteNumber(visual.visualDepthM,p.depthRadiusM*2))*scale,1)
    },
    radius:gdRound(Math.max(1,gdFiniteNumber(p.radius,0))*scale,1),
    lateralRadiusM:gdRound(Math.max(1,gdFiniteNumber(p.lateralRadiusM,0))*scale,1),
    depthRadiusM:gdRound(Math.max(1,gdFiniteNumber(p.depthRadiusM,0))*scale,1),
    displayScale:gdRound(scale,3),
    displayScaleReason:reason,
    rawRadiusM:gdRound(gdFiniteNumber(p.radius,0),1),
    rawLateralRadiusM:gdRound(gdFiniteNumber(p.lateralRadiusM,0),1),
    rawDepthRadiusM:gdRound(gdFiniteNumber(p.depthRadiusM,0),1)
  };
  return scaled;
}
function gdFallbackGpsBubblePayload(distance=155){
  const d=Math.max(1,gdFiniteNumber(distance,155));
  const minRadius=Math.max(1,gdFiniteNumber(dev("shotEngine.minimumBubbleRadiusM"),7));
  const baseRadius=Math.max(minRadius,d*gdFiniteNumber(dev("shotEngine.bubbleRadiusPct"),.082));
  const geo=typeof gdBubbleGeometryTuning==="function"?gdBubbleGeometryTuning():{widthScale:1,depthScale:1};
  const visualWidthM=Math.max(minRadius*2,baseRadius*1.72*geo.widthScale);
  const visualDepthM=Math.max(minRadius*2,baseRadius*2.12*geo.depthScale);
  const radius=Math.max(minRadius,visualWidthM/2,visualDepthM/2);
  return{
    club:"GPS",
    baseCarry:gdRound(d,1),
    totalM:gdRound(d,1),
    rolloutM:0,
    faceAlignmentOffsetDeg:0,
    faceOffsetDeg:0,
    aimOffsetDeg:0,
    aimOffsetM:0,
    clusterWidthM:gdRound(visualWidthM,1),
    clusterDepthM:gdRound(visualDepthM,1),
    clusterTiltDeg:0,
    faceWindowDeg:0,
    carryWindowPct:0,
    distanceTendencyPct:0,
    dispersionMultiplier:1,
    gdbTrust:0,
    visual:{
      visualWidthM:gdRound(visualWidthM,1),
      visualDepthM:gdRound(visualDepthM,1),
      visualTiltDeg:0,
      visualSkewDeg:0,
      visualYBias:0
    },
    radius:gdRound(radius,1),
    lateralRadiusM:gdRound(visualWidthM/2,1),
    depthRadiusM:gdRound(visualDepthM/2,1),
    source:"gps-default",
    shapeSource:"gps-fallback-default",
    playerId:"gps-default",
    engineAvailable:false
  };
}
function getGpsBubblePayload(distance=155){
  try{
    if(typeof getGDBForClub==="function")return gdNormalizeGpsBubblePayload(getGDBForClub("Bag",distance),distance);
  }catch(e){}
  return gdFallbackGpsBubblePayload(distance);
}
function gdGpsBubbleDisplayPayload(payload,distance=155,center=null){
  const p=gdBubblePayloadForRender(payload);
  const d=Math.max(1,gdFiniteNumber(distance,155));
  let lateral=Math.max(1,gdFiniteNumber(p.lateralRadiusM,gdFiniteNumber(p.visual&&p.visual.visualWidthM,p.radius*2)/2));
  let depth=Math.max(1,gdFiniteNumber(p.depthRadiusM,gdFiniteNumber(p.visual&&p.visual.visualDepthM,p.radius*2)/2));
  const fallbackLike=p.engineAvailable===false||p.source==="gps-default"||p.shapeSource==="gps-fallback-default";
  // Projection clamps are tunable from the Bubble Geometry board. Fallback
  // bubbles keep their legacy proportion of the tuned caps (10/13, 14/18).
  const geo=typeof gdBubbleGeometryTuning==="function"?gdBubbleGeometryTuning():{gpsMaxLateralPct:.13,gpsMaxDepthPct:.18,gpsMaxLateralM:28,gpsMaxDepthM:38,gpsPixelCapScale:1};
  const maxLateral=gdClamp(d*geo.gpsMaxLateralPct*(fallbackLike?10/13:1),9,geo.gpsMaxLateralM);
  const maxDepth=gdClamp(d*geo.gpsMaxDepthPct*(fallbackLike?14/18:1),12,geo.gpsMaxDepthM);
  const minLateral=gdClamp(d*.028,3.8,7.5);
  const minDepth=gdClamp(d*.038,5.2,11);
  let scale=Math.min(1,maxLateral/lateral,maxDepth/depth);
  if(scale<1){
    lateral*=scale;
    depth*=scale;
  }
  const minScale=Math.min(1,Math.max(minLateral/lateral,minDepth/depth));
  if(minScale>scale){
    scale=minScale;
    lateral=Math.max(lateral,minLateral);
    depth=Math.max(depth,minDepth);
  }
  try{
    if(map&&center&&typeof projectOffset==="function"){
      const size=map.getSize&&map.getSize();
      const maxPx=size?Math.max(42,Math.min(size.x<=560?86:138,size.x*(size.x<=560 ? .22 : .18),size.y*.18))*geo.gpsPixelCapScale:0;
      if(maxPx>0){
        const c=map.latLngToLayerPoint(center);
        const shotBrg=gdBubbleShotBearing();
        const depthPx=c.distanceTo(map.latLngToLayerPoint(projectOffset(center,shotBrg,depth,0)));
        const lateralPx=c.distanceTo(map.latLngToLayerPoint(projectOffset(center,shotBrg,0,lateral)));
        const pxMax=Math.max(depthPx,lateralPx);
        if(Number.isFinite(pxMax)&&pxMax>maxPx){
          scale*=maxPx/pxMax;
        }
      }
    }
  }catch(e){}
  scale=gdClamp(scale,.42,1.08);
  return Math.abs(scale-1)<.015?p:gdScaleGpsBubblePayloadForDisplay(p,scale);
}
function gdBubblePayloadForRender(input){
  if(input&&typeof input==="object"&&Number.isFinite(Number(input.radius)))return input;
  const radius=Math.max(gdFiniteNumber(dev("shotEngine.minimumBubbleRadiusM"),7),gdFiniteNumber(input,0));
  const payload=gdFallbackGpsBubblePayload(radius/gdFiniteNumber(dev("shotEngine.bubbleRadiusPct"),.082));
  payload.radius=gdRound(radius,1);
  payload.lateralRadiusM=gdRound(radius,1);
  payload.depthRadiusM=gdRound(radius,1);
  payload.visual.visualWidthM=gdRound(radius*2,1);
  payload.visual.visualDepthM=gdRound(radius*2,1);
  return payload;
}
function bubbleRadiusFactor(rel,payload=null){
  const front=Math.cos(rel);
  const frontPos=Math.max(0,front);
  const backPos=Math.max(0,-front);
  const tendency=payload?gdClamp(gdFiniteNumber(payload.distanceTendencyPct,0),-5,5)/5:0;
  const factor=1 + tendency*(0.026*frontPos - 0.018*backPos);
  return Math.max(.96, Math.min(1.04, factor));
}
function bubbleTextureFactor(rel,payload=null,intensity=1){
  if(!bubbleOrganic)return 1;
  const side=Math.sin(rel);
  const rightPos=Math.max(0,side);
  const leftPos=Math.max(0,-side);
  const frontPos=Math.max(0,Math.cos(rel));
  const tendency=payload?gdClamp(gdFiniteNumber(payload.distanceTendencyPct,0),-5,5)/5:0;
  let factor=1 + intensity*(0.012*Math.sin(rel*4 + .8) + 0.008*Math.sin(rel*7 - .35));
  if(bubbleBiasMode==="right"){
    factor += intensity*(0.018*rightPos - 0.008*leftPos);
  }else if(bubbleBiasMode==="left"){
    factor += intensity*(0.018*leftPos - 0.008*rightPos);
  }else if(bubbleBiasMode==="long"){
    factor += intensity*.018*frontPos;
  }
  factor += intensity*tendency*.01*frontPos;
  return Math.max(.97,Math.min(1.03,factor));
}
function gdBubbleShotBearing(){
  return (start&&target)?bearing(start,target):0;
}
function gdBubbleRoofMaxDistanceM(){
  try{
    const max=typeof gdMaxPlayableCarryM==="function"?gdMaxPlayableCarryM():null;
    return Number.isFinite(Number(max))&&Number(max)>0?Number(max):null;
  }catch(e){return null}
}
function gdBubbleForwardDistanceFromStart(point,shotBrg=gdBubbleShotBearing()){
  if(!start||!point||!map)return null;
  try{
    const distance=map.distance(start,point);
    const angle=bearing(start,point);
    const forward=Math.cos(normAng(angle-shotBrg))*distance;
    return Number.isFinite(forward)?forward:null;
  }catch(e){return null}
}
function gdBubbleDepthForRoof(payloadInput){
  const payload=gdBubblePayloadForRender(payloadInput);
  const visual=payload&&payload.visual&&typeof payload.visual==="object"?payload.visual:{};
  const depth=gdFiniteNumber(payload.depthRadiusM,gdFiniteNumber(visual.visualDepthM,gdFiniteNumber(payload.radius,0)*2)/2);
  return Math.max(1,Number(depth)||1);
}
function gdClampBubbleCenterToBagRoof(center,payloadInput){
  if(!center||!start||!target||!map)return center;
  if(typeof gdTournamentModeEnabled==="function"&&gdTournamentModeEnabled())return center;
  const maxDistance=gdBubbleRoofMaxDistanceM();
  if(!(maxDistance>0))return center;
  const shotBrg=gdBubbleShotBearing();
  const forward=gdBubbleForwardDistanceFromStart(center,shotBrg);
  if(!Number.isFinite(forward))return center;
  const roofDepth=gdBubbleDepthForRoof(payloadInput);
  const overshoot=forward+roofDepth-maxDistance;
  if(!(overshoot>.35))return center;
  try{
    const capBack=Math.max(0,forward-1);
    return projectOffset(center,shotBrg,-Math.min(overshoot,capBack),0);
  }catch(e){return center}
}
function gdShotDisplayTarget(){
  if(gdHasWindVector()&&gdWindLandingTarget)return gdWindLandingTarget;
  return target;
}
function gdBubbleRenderCenter(payloadInput){
  const renderTarget=gdShotDisplayTarget();
  if(!renderTarget)return null;
  const payload=gdBubblePayloadForRender(payloadInput);
  const shotBrg=gdBubbleShotBearing();
  const sideLimit=Math.max(2,gdFiniteNumber(payload.lateralRadiusM,payload.radius)*.78);
  const sideOffset=gdClamp(gdFiniteNumber(payload.aimOffsetM,0),-sideLimit,sideLimit);
  const forwardBias=gdClamp(gdFiniteNumber(payload.visual&&payload.visual.visualYBias,0),-.18,.18)*Math.max(1,gdFiniteNumber(payload.depthRadiusM,payload.radius));
  const rawCenter=projectOffset(renderTarget,shotBrg,forwardBias,sideOffset);
  return rawCenter;
}
function gdBubbleAxes(payloadInput,scale=1){
  const payload=gdBubblePayloadForRender(payloadInput);
  const lateral=Math.max(1,gdFiniteNumber(payload.lateralRadiusM,gdFiniteNumber(payload.visual&&payload.visual.visualWidthM,payload.radius*2)/2));
  const depth=Math.max(1,gdFiniteNumber(payload.depthRadiusM,gdFiniteNumber(payload.visual&&payload.visual.visualDepthM,payload.radius*2)/2));
  return{lateral:lateral*scale,depth:depth*scale};
}
function gdBubbleLocalToLatLng(center,payloadInput,x,y){
  const payload=gdBubblePayloadForRender(payloadInput);
  const tilt=((gdFiniteNumber(payload.visual&&payload.visual.visualTiltDeg,payload.clusterTiltDeg)||0)*Math.PI)/180;
  const skew=((gdFiniteNumber(payload.visual&&payload.visual.visualSkewDeg,0)||0)*Math.PI)/180;
  const skewedY=y + Math.tan(skew)*x*.42;
  const rx=x*Math.cos(tilt)-skewedY*Math.sin(tilt);
  const ry=x*Math.sin(tilt)+skewedY*Math.cos(tilt);
  return localPointToLatLng(center,gdBubbleShotBearing(),rx,ry);
}
function gdSmoothBubbleLocalRing(points,passes=2){
  if(!Array.isArray(points)||points.length<8)return points||[];
  let current=points.map(p=>({x:p.x,y:p.y}));
  for(let pass=0;pass<passes;pass++){
    current=current.map((point,index,all)=>{
      const prev=all[(index-1+all.length)%all.length];
      const next=all[(index+1)%all.length];
      return {
        x:point.x*.72+(prev.x+next.x)*.14,
        y:point.y*.72+(prev.y+next.y)*.14
      };
    });
  }
  return current;
}
function buildBubbleShape(center, payloadInput, scale=1){
  const payload=gdBubblePayloadForRender(payloadInput);
  const pts=[];
  const axes=gdBubbleAxes(payload,scale);
  const steps=168;
  for(let i=0;i<steps;i++){
    const rel=(Math.PI*2*i)/steps;
    const rf=bubbleRadiusFactor(rel,payload);
    pts.push({x:Math.cos(rel)*axes.depth*rf,y:Math.sin(rel)*axes.lateral*rf});
  }
  return gdSmoothBubbleLocalRing(pts,2).map(point=>gdBubbleLocalToLatLng(center,payload,point.x,point.y));
}
function localPointToLatLng(center, shotBrg, x, y){
  const ang=shotBrg + Math.atan2(y,x);
  const dist=Math.sqrt(x*x+y*y);
  return project(center, ang, dist);
}

/* ==== VERBATIM functions (gd-course-library-pin-lock.js) ==== */
  function sampleRouteProgress(route=[],stepM=7){
    const pts=route.map(toLatLng).filter(Boolean);
    if(!pts.length)return [];
    const samples=[{point:pts[0],progress:0}];
    let progress=0;
    for(let i=1;i<pts.length;i++){
      const a=pts[i-1],b=pts[i];
      const seg=distance(a,b);
      if(!Number.isFinite(seg)||seg<=0)continue;
      const brg=typeof bearing==='function'?bearing(a,b):Math.atan2(b.lng-a.lng,b.lat-a.lat);
      const steps=Math.max(1,Math.ceil(seg/Math.max(3,Number(stepM)||7)));
      for(let s=1;s<=steps;s++){
        const along=seg*(s/steps);
        const point=projectFramePoint(a,brg,along);
        if(point)samples.push({point,progress:progress+along});
      }
      progress+=seg;
    }
    return samples;
  }
  function fairwayLayupTargetByShotDistance(route=[],startLike,carryM){
    const startLL=toLatLng(startLike);
    const maxCarry=Number(carryM);
    const samples=sampleRouteProgress(route,7);
    if(!startLL||!(maxCarry>0)||samples.length<2)return null;
    let nearest=samples[0];
    samples.forEach(sample=>{
      const score=distance(startLL,sample.point);
      if(!nearest||score<nearest.score)nearest={...sample,score};
    });
    const minProgress=Math.max(0,Number(nearest?.progress)||0);
    let best=null;
    samples.forEach(sample=>{
      if(sample.progress<minProgress+6)return;
      const direct=distance(startLL,sample.point);
      if(!Number.isFinite(direct)||direct>maxCarry+3)return;
      const score=Math.abs(maxCarry-direct);
      if(!best||score<best.score-0.75||(Math.abs(score-best.score)<=0.75&&sample.progress>best.progress)){
        best={...sample,direct,score};
      }
    });
    if(!best||best.direct<Math.max(45,maxCarry*.58))return null;
    return best.point;
  }

  /* ==== adapter (fresh-app supplied, NOT copied) ====
     Only what the verbatim copies referenced from their old home:
     - start/target/greenCentre: shot state, fed by app.shot via the api.
     - dev(): reads the engine's own shipped DEV_DEFAULTS (no admin store in
       the fresh shell yet). Values copied from gd-app-core DEV_DEFAULTS.
     - map: distance() is the same haversine Leaflet's map.distance computes;
       getSize/latLngToLayerPoint route through the projection seam so the
       display payload's pixel cap sees the real on-surface scale.
     - wind, tournament, engine-payload globals the fresh shell does not run
       yet resolve to their engine-defined absence behaviour (declared, so
       verbatim copies take their intended branch rather than throwing).
     - window.gdMappedFairwayLayupTarget: in the old app pin-lock provides
       this seam; here the client provides it from the SAME verbatim layup
       helpers, fed the hole route the package already carries.
     - gdShotActiveProfile: the verbatim copy looks for a legacy account API
       (window.GolfDaddyAccounts / ClarityCaddieAccounts) that does not exist
       here. Rebinding it to read the fresh app's own bag store (set via
       GDBubbleEngine.setBag) is a function REASSIGNMENT, not a source edit —
       every copy above is still byte-identical to core, so the boot test's
       verbatim assertion still holds. bag.js owns the real storage/editor. */
  var start = null, target = null, greenCentre = null;
  var appBagRows = [];
  gdShotActiveProfile = function () { return appBagRows.length ? { bag: appBagRows } : null; };
  var targetDragging = false, bubbleOrganic = true, bubbleBiasMode = "neutral";
  var currentHoleNumber = 0, currentTee = null, currentRoute = [];
  var projection = null;   // {toScreen(latlng)->{x,y}, viewSize()->{x,y}}

  var DEV_DEFAULTS = {
    shotEngine: { bubbleRadiusPct: .082, minimumBubbleRadiusM: 7, distanceTendencyCapPct: 5, dispersionMultiplierCap: 1.6 },
    bubbleVisuals: { outerScale: 1.18, mainScale: 1.02, innerScale: .84, mainOutlineOpacity: .44, mainFillOpacity: .046, dragFillOpacity: .034, lockedShadeOpacity: .085, dragShadowOpacity: .18, classicOutlineOpacity: .78, classicFillOpacity: .065 },
    bubbleGeometry: {}
  };
  function dev(path) { return path.split(".").reduce(function (o, k) { return o && o[k]; }, DEV_DEFAULTS); }

  var map = {
    distance: function (a, b) { return window.ClarityApp.distance.haversineMeters(a, b); },
    getSize: function () {
      var size = projection && projection.viewSize && projection.viewSize();
      return size ? { x: size.x, y: size.y } : null;
    },
    latLngToLayerPoint: function (ll) {
      var pt = projection && projection.toScreen && projection.toScreen(ll);
      if (!pt) throw new Error("no projection");
      return L.point(pt.x, pt.y);
    }
  };

  /* Real wind state (wind.js drives it through setWind/clearWind below). The
     verbatim gdShotDisplayTarget/gdWindLandingFromAim/gdSyncWindLandingFromAim
     copies above already read exactly these three bindings by name. */
  var gdWindActive = false, gdWindOriginAngle = null, gdWindLevel = 1;
  var gdWindLandingTarget = null;
  function gdHasWindVector() { return !!gdWindActive && Number.isFinite(gdWindOriginAngle); }
  function activePlayerProfile() { return null; }
  function gdMappedStartHoleNumber() { return currentHoleNumber; }
  function toLatLng(value) {
    var lat = Number(value && value.lat), lng = Number(value && value.lng);
    return Number.isFinite(lat) && Number.isFinite(lng) ? { lat: lat, lng: lng } : null;
  }
  function distance(a, b) { return map.distance(a, b); }
  function projectFramePoint(origin, brg, meters) { return project(origin, brg, meters); }
  function gdMappedTeeAreaPoint() { return currentTee; }

  window.gdMappedFairwayLayupTarget = function (startLike, greenLike, carryM) {
    try {
      var startLL = toLatLng(startLike), greenLL = toLatLng(greenLike);
      var maxCarry = Number(carryM);
      if (!startLL || !greenLL || !(maxCarry > 0)) return null;
      if (distance(startLL, greenLL) <= maxCarry + 3) return greenLL;
      var route = (currentRoute || []).map(toLatLng).filter(Boolean);
      return fairwayLayupTargetByShotDistance(route, startLL, maxCarry) || null;
    } catch (e) { return null; }
  };

  window.GDBubbleEngine = {
    setHoleContext: function (ctx) {
      ctx = ctx || {};
      currentHoleNumber = Number(ctx.hole) || 0;
      currentTee = toLatLng(ctx.tee);
      currentRoute = Array.isArray(ctx.route) ? ctx.route : [];
      greenCentre = toLatLng(ctx.green);
    },
    setProjection: function (p) { projection = p || null; },
    setShot: function (startLL, targetLL) {
      start = toLatLng(startLL);
      target = toLatLng(targetLL);
      gdSyncWindLandingFromAim();
    },
    setDragging: function (on) { targetDragging = !!on; },
    setBag: function (rows) { appBagRows = Array.isArray(rows) ? rows : []; },
    defaultBagRows: gdDefaultStandInBag,
    setWind: function (originAngleRad, level) {
      gdWindActive = true;
      gdWindOriginAngle = gdNormAngle(Number(originAngleRad));
      gdWindLevel = Math.max(1, Math.min(3, Number(level) || 1));
      gdSyncWindLandingFromAim();
    },
    clearWind: function () {
      gdWindActive = false;
      gdWindLandingTarget = null;
    },
    windState: function () {
      return gdHasWindVector() ? { originAngle: gdWindOriginAngle, level: gdWindLevel } : null;
    },
    windLanding: function () { return gdWindLandingTarget; },
    maxPlayableCarryM: gdMaxPlayableCarryM,
    playableBag: gdPlayableShotBagRows,
    targetForGreenCentre: function (green, opts) { return gdTargetForGreenCentre(toLatLng(green), opts || {}); },
    /* The old renderShot pipeline, minus the Leaflet layers: distance →
       payload → render centre → display payload → the three shell rings as
       lat/lng arrays for the surface to project. */
    renderModel: function () {
      var displayTarget = gdShotDisplayTarget();
      if (!start || !displayTarget) return null;
      var d = map.distance(start, displayTarget);
      if (!Number.isFinite(d) || d <= 0) return null;
      var raw = getGpsBubblePayload(d);
      var center = gdBubbleRenderCenter(raw) || displayTarget || target;
      var gdb = gdGpsBubbleDisplayPayload(raw, d, center);
      return {
        distanceM: d,
        payload: gdb,
        center: center,
        rings: {
          outer: buildBubbleShape(center, gdb, dev("bubbleVisuals.outerScale")),
          main: buildBubbleShape(center, gdb, dev("bubbleVisuals.mainScale")),
          inner: buildBubbleShape(center, gdb, dev("bubbleVisuals.innerScale"))
        }
      };
    }
  };

})();
