#!/usr/bin/env node
/* Which Garmin watches Clarity Caddy ships on - derived, not hand-kept.
 *
 *   node garmin/tools/sync-devices.js           # rewrite manifest + jungle + icons
 *   node garmin/tools/sync-devices.js --check   # exit 1 if they are out of date
 *   node garmin/tools/sync-devices.js --list    # print the decision for every device
 *
 * The target is every WATCH with its own GPS that can actually run the app.
 * Each installed SDK device profile (~/Library/Application Support/Garmin/
 * ConnectIQ/Devices/<id>/compiler.json) is judged by four rules:
 *
 *   1. A watch. Edge bike computers and the GPSMAP / Oregon / Montana / Rino /
 *      eTrex handhelds are not.
 *   2. Its own GPS. The Legacy Hero / Legacy Saga watches use the phone's
 *      ("connected GPS"), and this app's whole job is position on the course.
 *      Profiles carry no GPS flag, so this one is a named list.
 *   3. Connect IQ >= the manifest's minSdkVersion (3.0.0): the 1.x/2.x watches
 *      lack APIs the app uses.
 *   4. A watch-app memory budget >= MIN_WATCH_APP_KB. Measured, not guessed:
 *      on 2026-10-05 the standalone sim demo idled at 101.7 of 123.8 KB on the
 *      fenix 6 (128 KB tier) and died "Out Of Memory" on its first Scene, before
 *      any hole map. The tiers are 96 / 128 / 512 / 768 / 1024 / 1280 KB, so the
 *      floor sits at 512.
 *
 * What it writes, between the GENERATED markers only:
 *   manifest.xml  - the <iq:product> list
 *   monkey.jungle - one resourcePath line per product, pointing at the launcher
 *                   icon folder of the width that device asks for
 *   resources-icons/<w>/ - any icon size not yet present, scaled from the 70 px
 *                   icon (itself the app icon cropped to the pin; README).
 */
"use strict";
const fs = require("fs");
const os = require("os");
const path = require("path");
const { execFileSync } = require("child_process");

const GARMIN = path.join(__dirname, "..");
const MANIFEST = path.join(GARMIN, "manifest.xml");
const JUNGLE = path.join(GARMIN, "monkey.jungle");
const ICONS = path.join(GARMIN, "resources-icons");
const DEVICES = process.env.CIQ_DEVICES || path.join(os.homedir(), "Library", "Application Support", "Garmin", "ConnectIQ", "Devices");

const NOT_WATCHES = ["edge", "gpsmap", "oregon", "montana", "rino", "etrex"];
const CONNECTED_GPS = ["legacyherocaptainmarvel", "legacyherofirstavenger", "legacysagadarthvader", "legacysagarey"];
const MIN_WATCH_APP_KB = 512;

const MARK_OPEN = "GENERATED by garmin/tools/sync-devices.js";
const MARK_CLOSE = "END GENERATED";

function versionTuple(v) { return String(v).split(".").map(Number); }
function versionAtLeast(v, min) {
  const a = versionTuple(v), b = versionTuple(min);
  for (let i = 0; i < 3; i++) { if ((a[i] || 0) !== (b[i] || 0)) return (a[i] || 0) > (b[i] || 0); }
  return true;
}

function minSdk() {
  const m = /minSdkVersion="([0-9.]+)"/.exec(fs.readFileSync(MANIFEST, "utf8"));
  return m ? m[1] : "3.0.0";
}

function judge(id, compiler, min) {
  if (NOT_WATCHES.some((p) => id.startsWith(p))) return "not a watch";
  if (CONNECTED_GPS.indexOf(id) >= 0) return "no GPS of its own (connected GPS)";
  const ciq = compiler.partNumbers.map((p) => p.connectIQVersion).reduce((a, b) => (versionAtLeast(a, b) ? a : b));
  if (!versionAtLeast(ciq, min)) return "Connect IQ " + ciq + " < " + min;
  const app = compiler.appTypes.find((t) => t.type === "watchApp");
  const kb = app ? Math.round(app.memoryLimit / 1024) : 0;
  if (kb < MIN_WATCH_APP_KB) return "watch-app memory " + kb + " KB < " + MIN_WATCH_APP_KB;
  return null;
}

function devices() {
  const min = minSdk();
  return fs.readdirSync(DEVICES).sort().map((id) => {
    const file = path.join(DEVICES, id, "compiler.json");
    if (!fs.existsSync(file)) return null;
    const compiler = JSON.parse(fs.readFileSync(file, "utf8"));
    return { id, name: compiler.displayName, icon: compiler.launcherIcon.width, excluded: judge(id, compiler, min) };
  }).filter(Boolean);
}

function replaceBetween(text, open, close, body, file) {
  const start = text.indexOf(open);
  const end = text.indexOf(close, start);
  if (start < 0 || end < 0) throw new Error(file + " has no generated block (" + open + " ... " + close + ")");
  const lineStart = text.lastIndexOf("\n", start) + 1;
  const after = text.indexOf("\n", end) + 1;
  return text.slice(0, lineStart) + body + text.slice(after);
}

function render(list) {
  const shipped = list.filter((d) => !d.excluded);
  const manifestBlock =
    "            <!-- " + MARK_OPEN + " (" + shipped.length + " watches). Edit the rules there, not this list. -->\n" +
    shipped.map((d) => '            <iq:product id="' + d.id + '"/>').join("\n") + "\n" +
    "            <!-- " + MARK_CLOSE + " -->\n";
  const jungleBlock =
    "# " + MARK_OPEN + ": one line per shipped watch, its launcher icon\n" +
    "# folder chosen by the width that device's own compiler.json asks for.\n" +
    shipped.map((d) => d.id + ".resourcePath = $(base.resourcePath);resources-icons/" + d.icon).join("\n") + "\n" +
    "# " + MARK_CLOSE + "\n";
  return { shipped, manifestBlock, jungleBlock };
}

function ensureIcon(width) {
  const dir = path.join(ICONS, String(width), "drawables");
  if (fs.existsSync(path.join(dir, "launcher_icon.png"))) return false;
  fs.mkdirSync(dir, { recursive: true });
  execFileSync("sips", ["-z", String(width), String(width), path.join(ICONS, "70", "drawables", "launcher_icon.png"),
    "--out", path.join(dir, "launcher_icon.png")], { stdio: "ignore" });
  fs.writeFileSync(path.join(dir, "drawables.xml"),
    "<drawables>\n    <!-- " + width + "x" + width + " launcher icon, scaled from the 70 px one by\n" +
    "         garmin/tools/sync-devices.js. See monkey.jungle for which devices take it. -->\n" +
    '    <bitmap id="LauncherIcon" filename="launcher_icon.png"/>\n</drawables>\n');
  return true;
}

if (!fs.existsSync(DEVICES)) {
  console.log("skipped: no Connect IQ device profiles at " + DEVICES + " (install the SDK's devices to sync)");
  process.exit(0);
}
const list = devices();
const mode = process.argv[2] || "";
if (mode === "--list") {
  list.forEach((d) => console.log((d.excluded ? "  -  " : "  +  ") + d.id.padEnd(26) + (d.excluded || "icon " + d.icon)));
  process.exit(0);
}
const { shipped, manifestBlock, jungleBlock } = render(list);
const manifestNow = fs.readFileSync(MANIFEST, "utf8");
const jungleNow = fs.readFileSync(JUNGLE, "utf8");
const manifestNext = replaceBetween(manifestNow, MARK_OPEN, MARK_CLOSE, manifestBlock, "manifest.xml");
const jungleNext = replaceBetween(jungleNow, MARK_OPEN, MARK_CLOSE, jungleBlock, "monkey.jungle");
if (mode === "--check") {
  const stale = manifestNext !== manifestNow || jungleNext !== jungleNow;
  console.log(stale ? "out of date: run node garmin/tools/sync-devices.js" : "up to date (" + shipped.length + " watches)");
  process.exit(stale ? 1 : 0);
}
fs.writeFileSync(MANIFEST, manifestNext);
fs.writeFileSync(JUNGLE, jungleNext);
const made = Array.from(new Set(shipped.map((d) => d.icon))).filter(ensureIcon);
console.log("shipping " + shipped.length + " watches; excluded " + (list.length - shipped.length) +
  (made.length ? "; new icon sizes " + made.join(", ") : ""));
